### ISSUE TITLE
Shallow or stub of CamelCase components isn't working

### ISSUE THREAD

**Issue by Akryum** [vuejs/vue-test-utils#105]
When using `shallow` or `stubs`, CamelCase components in the template are skipped.

# Example

```js
Vue.component('base-icon', ...)
Vue.component('BaseIcon', ...)
```

<details>
<summary>Tested component</summary>

```vue
<template>
  <component
    :is="component.is"
    v-bind="component.props"
    :disabled="finalDisabled"
    class="base-button"
    @click="onClick"
  >
    <span v-if="loading" class="loader light"></span>
    <span v-else>
      <BaseIcon v-if="icon" :id="icon" />
      <slot />
    </span>
  </component>
</template>

<script>
export default {
  props: {
    disabled: {
      type: Boolean,
      default: false,
    },
    href: {
      type: String,
      default: null,
    },
    icon: {
      type: String,
      default: null,
    },
    loading: {
      type: Boolean,
      default: false,
    },
    to: {
      type: Object,
      default: null,
    },
    type: {
      type: String,
      default: 'submit',
    },
  },

  computed: {
    component () {
      if (this.to) {
        return {
          is: 'router-link',
          props: {
            to: this.to,
          },
        }
      } else if (this.href) {
        return {
          is: 'a',
          props: {
            href: this.href,
          },
        }
      } else {
        return {
          is: 'button',
          props: {
            type: this.type,
          },
        }
      }
    },

    finalDisabled () {
      return this.disabled || this.loading
    },
  },

  methods: {
    onClick (event) {
      if (!this.finalDisabled) {
        this.$emit('click', event)
      }
    },
  },
}
</script>
```

</details>

## Working

Kebab-case version works fine:

```html
<div>
  <base-icon :id="icon" />
</div>
```

```js
const wrapper = shallow(Working, {
  propsData: {
    icon: 'foo',
  },
})
expect(wrapper.contains('base-icon')).toBe(true)
const icon = wrapper.find('base-icon')
expect(icon.hasAttribute('id', 'foo')).toBe(true)
```

## Not working

Came-case version fails:

```html
<div>
  <BaseIcon :id="icon" />
</div>
```

```js
const wrapper = shallow(NotWorking, {
  propsData: {
    icon: 'foo',
  },
})
expect(wrapper.contains('BaseIcon')).toBe(true)
const icon = wrapper.find('BaseIcon')
expect(icon.hasAttribute('id', 'foo')).toBe(true)
```

```js
const wrapper = mount(NotWorking, {
  propsData: {
    icon: 'foo',
  },
 stubs: ['BaseIcon'],
})
expect(wrapper.contains('BaseIcon')).toBe(true)
const icon = wrapper.find('BaseIcon')
expect(icon.hasAttribute('id', 'foo')).toBe(true)
```

```js
const wrapper = mount(NotWorking, {
  propsData: {
    icon: 'foo',
  },
  stubs: {
    BaseIcon: true,
  },
})
expect(wrapper.contains('BaseIcon')).toBe(true)
const icon = wrapper.find('BaseIcon')
expect(icon.hasAttribute('id', 'foo')).toBe(true)
```

Also, when calling `wrapper.html()`, the `<BaseIcon />` component is not present in the result HTML.

# Workaround

```js
describe('Test', () => {
  test('icon', () => {
    const wrapper = shallow(BaseButton, {
      propsData: {
        icon: 'foo',
      },
      stubs: {
        BaseIcon: '<stub-icon />',
      },
    })
    console.log(wrapper.html())
    expect(wrapper.contains('stub-icon')).toBe(true)
    const icon = wrapper.find('stub-icon')
    expect(icon.hasAttribute('id', 'foo')).toBe(true)
  })
})
```

**Comment by eddyerburgh** [comment]
Does it work with mount?

**Comment by eddyerburgh** [comment]
To find a component, you need to pass it the component object.

So In your test file, you'll need to import your BaseIcon component, and pass it to find:

```js
import BaseIcon from '~/BaseIcon'

const wrapper = mount(NotWorking, {
  propsData: {
    icon: 'foo',
  },
 stubs: ['BaseIcon'],
})
expect(wrapper.contains(BaseIcon)).toBe(true)
```

**Comment by Akryum** [comment]
What I'm trying to do is to shallow the button component so that the `BaseIcon` component will appear as `<BaseIcon id="foo"/>`.

**Comment by eddyerburgh** [comment]
Can you make a minimal reproducible example with a failing test that you think should pass? 

The examples you've posted are using strings to find components, which is not the way that vue-test-utils searches for instances.

**Comment by Akryum** [comment]
How do you stub those components then? I don't want their template to be in the snapshots for example.

**Comment by Akryum** [comment]
I tried this:

```js
test('icon 2', () => {
  const BaseIcon = Vue.component('BaseIcon')
  const wrapper = mount(BaseButton, {
    propsData: {
      iconRight: 'foo',
    },
    stubs: ['BaseIcon'],
  })
  expect(wrapper.contains(BaseIcon)).toBe(true)
  const icon = wrapper.find(BaseIcon)
  expect(icon.hasProp('id', 'foo')).toBe(true)
})
```

And I get the following error:

```
[vue-test-utils]: wrapper.contains() must be passed a valid CSS selector or a Vue constructor
      at throwError (node_modules/vue-test-utils/dist/vue-test-utils.js:12:9)
      at VueWrapper.contains (node_modules/vue-test-utils/dist/vue-test-utils.js:547:5)
```

I will make a repro when I have some time.

**Comment by eddyerburgh** [comment]
The way that `find` works with instances is to search by the component name. This is a limitation at the moment. We should probably add a warning that the component needs a name to be used as a selector.

When you stub a component, you can use the original component that you stubbed as a selector. 
```js
test('icon 2', () => {
import SomeComponent from '~/some-component'
  const wrapper = mount(BaseButton, {
    stubs: ['SomeComponent'],
  })
  expect(wrapper.contains(SomeComponent)).toBe(true)
  const icon = wrapper.find(SomeComponent)
})
```

**Comment by eddyerburgh** [comment]
I'm going to close this issue, as this isn't a bug.

There are three ways to select a Vue component:

Using a component:
```
import Component from './Component.vue'

const Selector = Component
```

Using a name:
```
const Selector = {
  name: 'component-name'
}
```

And using a ref:
```
const Selector = {
  ref: 'foo'
}
```
