### ISSUE TITLE
Calling setMethods on Wrapper throws error 'Cannot read property $options of undefined' when component is not visible

### ISSUE THREAD

**Issue by chrislutw** [vuejs/vue-test-utils#1091]
### Version
1.0.0-beta.28

### Reproduction link
[https://github.com/chrislutw/vue-test-utils-issue](https://github.com/chrislutw/vue-test-utils-issue)

### Steps to reproduce

```shell
npm i
npm test
```

### What is actually happening?
i want to use setMethods to mock component's button clickhandle, it's work in Btn.vue, but, BtnError.vue(base on Btn.vue) is's add ``v-if`` condition default is false and i turn it on ``wrapper.vm.visible = true`` and it still not working.

Calling setMethods on Wrapper throws error 'Cannot read property $options of undefined' 

why? 

do i miss some step?

**Comment by chrislutw** [comment]
BtnError.vue
```html
<template>
  <button v-if="visible" @click="handleClick">{{ label }}</button>
</template>

<script>
export default {
  name: "Button",
  props: {
    label: {
      type: String,
      required: true
    }
  },
  data: () => ({
    clicked: false,
    visible: false
  }),
  methods: {
    handleClick() {
      this.clicked = true;
    }
  }
};
</script>
```

BtnError.spec.js
```js
.
.
.
  test('calls handleClick on click', () => {
    const wrapper = factory()
    const handleClickMock = jest.fn()
    wrapper.vm.visible = true
    wrapper.setMethods({
      handleClick: handleClickMock
    })
    wrapper.find('button').trigger('click')
    expect(handleClickMock).toHaveBeenCalled()
  })
.
.
.
```

Btn.vue
```html
<template>
  <button @click="handleClick">{{ label }}</button>
</template>
.
.
.
```

Btn.spec.js
```js
.
.
.
  test('calls handleClick on click', () => {
    const wrapper = factory()
    const handleClickMock = jest.fn()
    wrapper.setMethods({
      handleClick: handleClickMock
    })
    wrapper.find('button').trigger('click')
    expect(handleClickMock).toHaveBeenCalled()
  })
.
.
.
```

**Comment by eddyerburgh** [comment]
I can't reproduce by running your reproduction. Can you check that it includes the bug?

**Comment by chrislutw** [comment]
Sorry to disturb you, it's not includes the bug, my bad. 
one more question , is possible to setMethods on non visible component?
when i comment line 25, wrapper will throws error

[BtnError.spec.js](https://github.com/chrislutw/vue-test-utils-issue/blob/master/components/BtnError/BtnError.spec.js)
      
```
// wrapper.vm.visible = true
```

**Comment by ilearnio** [comment]
@chrislutw So what was the solution? Having the same problem. Component is visible in my case

```js
import Vuex from 'vuex';
import sinon from 'sinon';
import { createLocalVue, mount } from '@vue/test-utils';

const wrap = ({ store, propsData, mocks }) => {
  const localVue = createLocalVue();
  localVue.use(Vuex);

  const Component = localVue.extend({
    render: () => '',
    mixins: [BroadcastItemMixin],
  });

  return mount(Component, {
    localVue,
    store: new Vuex.Store(store),
    propsData,
    mocks,
  });
};

context('when broadcast frequency present', () => {
  let wrapper;
  beforeEach(() => {
    wrapper = wrap({ store, propsData: { broadcast: { frequency: '123' } } });
    wrapper.setMethods({ throttledBroadcastShown: sinon.spy() }); // <-- ERROR HERE !!!!!!!!!!
  });
});
```

```
TypeError: Cannot read property '$options' of undefined
      at VueWrapper.setMethods (dist/webpack:/node_modules/@vue/test-utils/dist/vue-test-utils.js:10625:1)
      at Context.beforeEach (dist/webpack:/tests/unit/components/mixins/BroadcastItemMixin.test.js:107:1)
```

**Comment by ilearnio** [comment]
It appeared that it was because my `render` function was returning an empty string. So this is how I fixed it.

```js
  const Component = localVue.extend({
    render: c => c('div'),
    mixins: [BroadcastItemMixin],
  });
```
