### ISSUE TITLE
TypeError: Cannot read property 'dev' of undefined

### ISSUE THREAD

**Issue by ppvy** [vuejs/vue-test-utils#1102]
### Version
1.0.0-beta.28

### Reproduction link
[https://jsfiddle.net/yoonasy/xL6hwd7a/1/](https://jsfiddle.net/yoonasy/xL6hwd7a/1/)

```
import HotVideoComponent from 'workbench/hot-video/hot-video.vue'
import { shallowMount, mount } from '@vue/test-utils'
import { expect } from 'chai'

describe('foo', () => {
  it('test hotVideo', () => {
    let wrapper = mount(HotVideoComponent)

    wrapper.setData({
      footer: { Code: -6, Msg: 'test 测试~~~~~~~~' }
    })

    expect(wrapper.find('.page-footer-wrap p').text()).toBe('test 测试~~~~~~~~')
  })
})

```

### Steps to reproduce
.

### What is expected?
is ok

### What is actually happening?
error

```
MOCHA  Testing...

RUNTIME EXCEPTION  Exception occurred while loading your tests

TypeError: Cannot read property 'dev' of undefined
    at Module../src/libs/api.js (I:\Desktop\tiktop\dist\webpack:\src\libs\api.js:12:1)
    at __webpack_require__ (I:\Desktop\tiktop\dist\webpack:\webpack\bootstrap:25:1)
    at Module../src/conf/popup.js (I:\Desktop\tiktop\dist\webpack:\src\conf\popup.js:1:1)
    at __webpack_require__ (I:\Desktop\tiktop\dist\webpack:\webpack\bootstrap:25:1)
    at Module../src/libs/axios.js (I:\Desktop\tiktop\dist\main.js:118873:69)
    at __webpack_require__ (I:\Desktop\tiktop\dist\webpack:\webpack\bootstrap:25:1)
    at Module../src/libs/utils.js (I:\Desktop\tiktop\dist\main.js:119726:64)
    at __webpack_require__ (I:\Desktop\tiktop\dist\webpack:\webpack\bootstrap:25:1)
    at Module../src/conf/index.js (I:\Desktop\tiktop\dist\webpack:\src\conf\index.js:1:1)
    at __webpack_require__ (I:\Desktop\tiktop\dist\webpack:\webpack\bootstrap:25:1)
    at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/views/workbench/hot-video/hot-video.vue?vue&type=script&lang=js& (I:\Desktop\tiktop\dist\main.js:15057:63)
    at __webpack_require__ (I:\Desktop\tiktop\dist\webpack:\webpack\bootstrap:25:1)
    at Module../src/views/workbench/hot-video/hot-video.vue?vue&type=script&lang=js& (I:\Desktop\tiktop\dist\webpack:\src\views\workbench\hot-video\hot-video.vue?0ea7:1:1)
    at __webpack_require__ (I:\Desktop\tiktop\dist\webpack:\webpack\bootstrap:25:1)
    at Module../src/views/workbench/hot-video/hot-video.vue (I:\Desktop\tiktop\dist\webpack:\src\views\workbench\hot-video\hot-video.vue:1:1)
    at __webpack_require__ (I:\Desktop\tiktop\dist\webpack:\webpack\bootstrap:25:1)
    at Module../tests/unit/temp.spec.js (I:\Desktop\tiktop\dist\webpack:\tests\unit\temp.spec.js:1:1)
    at __webpack_require__ (I:\Desktop\tiktop\dist\webpack:\webpack\bootstrap:25:1)
    at run (I:\Desktop\tiktop\dist\webpack:\node_modules\mocha-webpack\lib\entry.js:3:1)
    at Array.forEach (<anonymous>)
    at Object../node_modules/mocha-webpack/lib/entry.js (I:\Desktop\tiktop\dist\webpack:\node_modules\mocha-webpack\lib\entry.js:10:1)
    at __webpack_require__ (I:\Desktop\tiktop\dist\webpack:\webpack\bootstrap:25:1)
    at I:\Desktop\tiktop\dist\webpack:\webpack\bootstrap:116:1
    at Object.<anonymous> (I:\Desktop\tiktop\dist\main.js:120:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object._module2.default._extensions.(anonymous function) [as .js] (I:\Desktop\tiktop\node_modules\mocha-webpack\lib\util\registerRequireHook.js:148:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at I:\Desktop\tiktop\node_modules\mocha\lib\mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (I:\Desktop\tiktop\node_modules\mocha\lib\mocha.js:247:14)
    at Mocha.run (I:\Desktop\tiktop\node_modules\mocha\lib\mocha.js:576:10)
    at runMocha (I:\Desktop\tiktop\node_modules\mocha-webpack\lib\runner\TestRunner.js:244:35)
    at I:\Desktop\tiktop\node_modules\mocha-webpack\lib\runner\TestRunner.js:300:13
    at I:\Desktop\tiktop\node_modules\mocha-webpack\lib\webpack\compiler\registerReadyCallback.js:26:7
    at AsyncSeriesHook.eval [as callAsync] (eval at create (I:\Desktop\tiktop\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:36:1)
    at Watching._done (I:\Desktop\tiktop\node_modules\webpack\lib\Watching.js:97:28)
    at compiler.emitRecords.err (I:\Desktop\tiktop\node_modules\webpack\lib\Watching.js:72:19)
    at Compiler.emitRecords (I:\Desktop\tiktop\node_modules\webpack\lib\Compiler.js:375:39)
    at compiler.emitAssets.err (I:\Desktop\tiktop\node_modules\webpack\lib\Watching.js:53:20)
    at hooks.afterEmit.callAsync.err (I:\Desktop\tiktop\node_modules\webpack\lib\Compiler.js:361:14)
    at _err0 (eval at create (I:\Desktop\tiktop\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:11:1)
    at callback (I:\Desktop\tiktop\node_modules\copy-webpack-plugin\dist\index.js:126:17)
    at afterEmit (I:\Desktop\tiktop\node_modules\copy-webpack-plugin\dist\index.js:220:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (I:\Desktop\tiktop\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:7:1)
    at asyncLib.forEach.err (I:\Desktop\tiktop\node_modules\webpack\lib\Compiler.js:358:27)
    at I:\Desktop\tiktop\node_modules\neo-async\async.js:2825:7
    at done (I:\Desktop\tiktop\node_modules\neo-async\async.js:2861:11)
    at I:\Desktop\tiktop\node_modules\neo-async\async.js:2813:7
    at MemoryFileSystem.writeFile (I:\Desktop\tiktop\node_modules\memory-fs\lib\MemoryFileSystem.js:328:9)
    at writeOut (I:\Desktop\tiktop\node_modules\webpack\lib\Compiler.js:342:29)
    at Immediate._onImmediate (I:\Desktop\tiktop\node_modules\memory-fs\lib\MemoryFileSystem.js:288:4)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by ppvy** [comment]
config use default

**Comment by eddyerburgh** [comment]
Can you provide a runnable reproduction, preferably in the form of a GitHub repo.

**Comment by ppvy** [comment]
@eddyerburgh 
Integrated into corporate projects,

Can I send any private messages

**Comment by eddyerburgh** [comment]
Can you extract the problem code and create a minimum reproduction with as little code as possible? It's more difficult to debug in large projects, and also sometimes in the process of creating a reproduction people realize that the bug was in their code.

**Comment by eddyerburgh** [comment]
Please open a new issue with the reproduction, if you are able to create one.
