### ISSUE TITLE
vue 2.6+  named slot and pug will make jest broken

### ISSUE THREAD

**Issue by yoyoys** [vuejs/vue-test-utils#1210]
### Version
1.0.0-beta.29

### Reproduction link
[https://github.com/yoyoys/vue-slot-pug-bug-jest-reproduction](https://github.com/yoyoys/vue-slot-pug-bug-jest-reproduction)

### Steps to reproduce
1. create project by vue-cli 3.6.3, using jest, TypeScript, TSLint, Class Component
2. `npm i -D pug pug-plain-loader`
3. add a component which has named slot (SlotGuy.vue)
4. run `npm run test:unit`

### What is expected?
test run success

### What is actually happening?
I've got a error below:
```
  ● Test suite failed to run

    SyntaxError: Unexpected character '#' (1:150)

      at Parser.pp$4.raise (node_modules/vue-template-es2015-compiler/buble.js:2757:13)
      at Parser.pp$8.getTokenFromCode (node_modules/vue-template-es2015-compiler/buble.js:4906:8)
      at Parser.pp$8.readToken (node_modules/vue-template-es2015-compiler/buble.js:4628:15)
      at Parser.readToken (node_modules/vue-template-es2015-compiler/buble.js:6029:22)
      at Parser.pp$8.nextToken (node_modules/vue-template-es2015-compiler/buble.js:4619:15)
      at Parser.pp$8.next (node_modules/vue-template-es2015-compiler/buble.js:4576:8)
      at Parser.pp.eat (node_modules/vue-template-es2015-compiler/buble.js:577:10)
      at Parser.pp.expect (node_modules/vue-template-es2015-compiler/buble.js:641:8)
      at Parser.pp$1.parseFunctionParams (node_modules/vue-template-es2015-compiler/buble.js:1230:8)
      at Parser.pp$1.parseFunction (node_modules/vue-template-es2015-compiler/buble.js:1218:8)

```

**Comment by yoyoys** [comment]
workround here: 
replace
```pug
template(#boom)
```
into this
```pug
template(#boom="")
```

**Comment by eddyerburgh** [comment]
Thanks for this, this bug will need to be fixed in vue-jest, so I've moved your issue there: https://github.com/vuejs/vue-test-utils/issues/1210

**Comment by yoyoys** [comment]
related: https://github.com/vuejs/vue-jest/issues/175
