### ISSUE TITLE
`basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")`  when importing vue-test-utils

### ISSUE THREAD

**Issue by nolde** [vuejs/vue-test-utils#122]
When importing `vue-test-utils`, I get a weird error that doesn't seem to be related to anything else other than the component itself. I am running the test with `jest`.

Test code:
```javascript
import { shallow, createLocalVue } from 'vue-test-utils'

describe('App', () => {
  it('should work', () => {
    expect(true).toBe(true)
  })
})
```

If the import line is commented out, the test runs fine and passes; with the import in, I get the following error:

```bash
 FAIL  src\core\App.test.js
  ● Test suite failed to run

    C:\Program Files\nodejs\vue:2
    basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
              ^^^^^^^
    SyntaxError: missing ) after argument list

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)
      at Object.<anonymous> (node_modules/vue-test-utils/dist/vue-test-utils.js:5:27)
      at Object.<anonymous> (src/core/App.test.js:2:21)
```

I have removed the node_modules folder and reinstalled it all using `npm install` to make sure it was not a dependency issue.

Jest config:
```json
// package.json
  "jest": {
    "moduleFileExtensions": [
      "js",
      "vue"
    ],
    "moduleNameMapper": {
      "^@/(.*)$": "<rootDir>/src/$1"
    },
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/babel-jest",
      ".*\\.(vue)$": "<rootDir>/node_modules/jest-vue"
    },
    "mapCoverage": true,
    "verbose": true
  }
```

Versions:
- Windows 10
- `npm v3.10.10`
- `node v6.10.3`
- `vue v2.5.2`
- `babel-jest v21.2.0`
- `jest v21.2.1`
- `jest-vue v0.8.1`
- `vue-test-utils` with `v1.0.0.beta.3`, `v1.0.0.beta.2`, `v1.0.0.beta.1`

**Comment by nolde** [comment]
I am closing this.

When trying to create tests without using vue-test-utils, I got the same error when mounting my component; that means the problem lies within the jest/vue ecosystem.

**Comment by nolde** [comment]
The problem seems to be with jest runtime in Windows.

https://github.com/facebook/jest/issues/4751
