### ISSUE TITLE
TypeError on error handler

### ISSUE THREAD

**Issue by johnsudaar** [vuejs/vue-test-utils#1222]
### Version
1.0.0-beta.29

### What is actually happening?

---
Unfortunately i've not been able to find a minimal reproduction setup.

But for some reason, `vm` is undefined when errorHandler is called (https://github.com/vuejs/vue-test-utils/blob/dev/packages/test-utils/src/error.js#L4)

Resuling in a type error when doing `vm._error`. This is pretty bad because the "real" error is then lost making the app impossible to debug.

Here is the stack trace:
```
TypeError: Cannot set property '_error' of undefined                                                                             
    at errorHandler (/home/john/Documents/Scalingo/dashboard-vue/dist/webpack:/node_modules/@vue/test-utils/dist/vue-test-utils.js:3152:1)
    at globalHandleError (/home/john/Documents/Scalingo/dashboard-vue/dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:1723:1)                                                 
    at handleError (/home/john/Documents/Scalingo/dashboard-vue/dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:1717:1)
    at Array.<anonymous> (/home/john/Documents/Scalingo/dashboard-vue/dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:1835:1)                
    at flushCallbacks (/home/john/Documents/Scalingo/dashboard-vue/dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:1754:1)     
```

I think that a check on `vm` should be sufficient to at least not hide the real error.

**Comment by Alex-Sokolov** [comment]
I also have this problem. And when you run tests in the file, everything is ok, but when you run tests on the whole project it is shown.

Error handler receives the third parameter the information where the error occurred. I changed the VTU source code to look at it, and in this case the error occurs in 'nextTick'.

How I changed vue-test-utils.js:
```
function errorHandler(errorOrString, vm, info) {
  var error =
    typeof errorOrString === 'object' ? errorOrString : new Error(errorOrString);

  if (vm) {
    vm._error = error;
  } else {
    console.log('TEST', vm, info) // <-- added
  }

  throw error
}
```

```
  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "TEST undefined nextTick".

      at BufferedConsole.log (node_modules/@jest/console/build/BufferedConsole.js:201:10)
      at errorHandler (node_modules/@vue/test-utils/dist/vue-test-utils.js:2901:13)
      at globalHandleError (node_modules/vue/dist/vue.runtime.common.dev.js:1866:34)
      at handleError (node_modules/vue/dist/vue.runtime.common.dev.js:1835:5)
      at Array.<anonymous> (node_modules/vue/dist/vue.runtime.common.dev.js:1978:9)
      at flushCallbacks (node_modules/vue/dist/vue.runtime.common.dev.js:1902:14)


  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'createElement' of null"".

      at BufferedConsole.error (node_modules/@jest/console/build/BufferedConsole.js:165:10)
      at warn (node_modules/vue/dist/vue.runtime.common.dev.js:621:15)
      at logError (node_modules/vue/dist/vue.runtime.common.dev.js:1880:5)
      at globalHandleError (node_modules/vue/dist/vue.runtime.common.dev.js:1875:3)
      at handleError (node_modules/vue/dist/vue.runtime.common.dev.js:1835:5)
      at Array.<anonymous> (node_modules/vue/dist/vue.runtime.common.dev.js:1978:9)
      at flushCallbacks (node_modules/vue/dist/vue.runtime.common.dev.js:1902:14)


  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "TypeError: Cannot read property 'createElement' of null
        at Object.createElement$1 [as createElement] (/Users/Modex/Work/project/node_modules/vue/dist/vue.runtime.common.dev.js:5665:22)
        at createElm (/Users/Modex/Work/project/node_modules/vue/dist/vue.runtime.common.dev.js:5929:19)
        at VueComponent.patch [as __patch__] (/Users/Modex/Work/project/node_modules/vue/dist/vue.runtime.common.dev.js:6455:7)
        at VueComponent.Vue._update (/Users/Modex/Work/project/node_modules/vue/dist/vue.runtime.common.dev.js:3933:19)
        at VueComponent.updateComponent (/Users/Modex/Work/project/node_modules/vue/dist/vue.runtime.common.dev.js:4054:10)
        at Watcher.get (/Users/Modex/Work/project/node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
        at new Watcher (/Users/Modex/Work/project/node_modules/vue/dist/vue.runtime.common.dev.js:4454:12)
        at mountComponent (/Users/Modex/Work/project/node_modules/vue/dist/vue.runtime.common.dev.js:4061:3)
        at VueComponent.Vue.$mount (/Users/Modex/Work/project/node_modules/vue/dist/vue.runtime.common.dev.js:8392:10)
        at init (/Users/Modex/Work/project/node_modules/vue/dist/vue.runtime.common.dev.js:3112:13)
        at createComponent (/Users/Modex/Work/project/node_modules/vue/dist/vue.runtime.common.dev.js:5958:9)
        at createElm (/Users/Modex/Work/project/node_modules/vue/dist/vue.runtime.common.dev.js:5905:9)
        at updateChildren (/Users/Modex/Work/project/node_modules/vue/dist/vue.runtime.common.dev.js:6196:11)
        at patchVnode (/Users/Modex/Work/project/node_modules/vue/dist/vue.runtime.common.dev.js:6299:29)
        at VueComponent.patch [as __patch__] (/Users/Modex/Work/project/node_modules/vue/dist/vue.runtime.common.dev.js:6460:9)
        at VueComponent.Vue._update (/Users/Modex/Work/project/node_modules/vue/dist/vue.runtime.common.dev.js:3936:19)
        at VueComponent.updateComponent (/Users/Modex/Work/project/node_modules/vue/dist/vue.runtime.common.dev.js:4054:10)
        at Watcher.get (/Users/Modex/Work/project/node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
        at Watcher.run (/Users/Modex/Work/project/node_modules/vue/dist/vue.runtime.common.dev.js:4540:22)
        at flushSchedulerQueue (/Users/Modex/Work/project/node_modules/vue/dist/vue.runtime.common.dev.js:4298:13)
        at Array.<anonymous> (/Users/Modex/Work/project/node_modules/vue/dist/vue.runtime.common.dev.js:1976:12)
        at flushCallbacks (/Users/Modex/Work/project/node_modules/vue/dist/vue.runtime.common.dev.js:1902:14)".

      at Object.createElement$1 [as createElement] (node_modules/vue/dist/vue.runtime.common.dev.js:5665:22)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:5929:19)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6455:7)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3933:19)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4054:10)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:4454:12)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4061:3)
      at VueComponent.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8392:10)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:3112:13)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:5958:9)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:5905:9)
      at updateChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6196:11)
      at patchVnode (node_modules/vue/dist/vue.runtime.common.dev.js:6299:29)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6460:9)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3936:19)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4054:10)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
      at Watcher.run (node_modules/vue/dist/vue.runtime.common.dev.js:4540:22)
      at flushSchedulerQueue (node_modules/vue/dist/vue.runtime.common.dev.js:4298:13)
      at Array.<anonymous> (node_modules/vue/dist/vue.runtime.common.dev.js:1976:12)
      at flushCallbacks (node_modules/vue/dist/vue.runtime.common.dev.js:1902:14)".
      at BufferedConsole.error (node_modules/@jest/console/build/BufferedConsole.js:165:10)
      at logError (node_modules/vue/dist/vue.runtime.common.dev.js:1884:13)
      at globalHandleError (node_modules/vue/dist/vue.runtime.common.dev.js:1875:3)
      at handleError (node_modules/vue/dist/vue.runtime.common.dev.js:1835:5)
      at Array.<anonymous> (node_modules/vue/dist/vue.runtime.common.dev.js:1978:9)
      at flushCallbacks (node_modules/vue/dist/vue.runtime.common.dev.js:1902:14)

```
