### ISSUE TITLE
createLocalVue :  TypeError: Cannot set property 'installed' of undefined for Vuetify

### ISSUE THREAD

**Issue by gkatsanos** [vuejs/vue-test-utils#130]
Just did this:
```js
import { mount, createLocalVue } from 'vue-test-utils';
import Vuetify from 'vuetify';

const localVue = createLocalVue();
localVue.use(Vuetify);

describe('Question.spec.js', () => {
  let cmp;
  let template;
  
  beforeEach(() => {
    cmp = mount(Question, {
      localVue,
      propsData: {
        question: {},
        id: "/questions/6673",
      store,
    });
    template = cmp.html();
  });
```

And I get
```

    TypeError: Cannot set property 'installed' of undefined

      at Function.instance.use (node_modules/vue-test-utils/dist/vue-test-utils.js:1253:30)
      at Object.<anonymous> (src/components/Question/Question.spec.js:8:10)
          at Generator.next (<anonymous>)
          at Promise (<anonymous>)
          at Generator.next (<anonymous>)
          at <anonymous>
```

**Comment by nekosaur** [comment]
@gkatsanos Are you using one of Vuetify's templates with a-la-carte components enabled?

**Comment by gkatsanos** [comment]
@nekosaur no, I am using the entire thing. (but you see that from my message right?)

**Comment by eddyerburgh** [comment]
I'll fix this bug tomorrow 🙂

**Comment by eddyerburgh** [comment]
This is fixed in the dev branch, I'll get it released tonight around 21:00 GMT

**Comment by gkatsanos** [comment]
The error is gone but I'm not sure the use works.
```
import Vuex from 'vuex';
import Vuetify from 'vuetify';
import { shallow, createLocalVue } from 'vue-test-utils';
import QuestionsList from './QuestionsList';

const localVue = createLocalVue();

localVue.use(Vuex);
localVue.use(Vuetify);
```

I made a snapshot of this and it's empty:
exports[`QuestionsList.spec.js has the expected html structure 1`] = `
<div>
    <h4>Questions</h4>
    
    
</div>
`;

**Comment by lukaszkups** [comment]
I've got similar issue:


```
TypeError: Cannot set property '_error' of undefined
    at errorHandler (node_modules/@vue/test-utils/dist/vue-test-utils.js:4026:13)
    at globalHandleError (node_modules/vue/dist/vue.runtime.common.js:1701:34)
    at handleError (node_modules/vue/dist/vue.runtime.common.js:1695:3)
    at Array.<anonymous> (node_modules/vue/dist/vue.runtime.common.js:1813:9)
    at flushCallbacks (node_modules/vue/dist/vue.runtime.common.js:1732:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
{ AssertionError: expected false to be true
    at .tmp/mocha-webpack/1516627397657/test/specs/ChatStatusBar.spec.js:53:1
    at Array.<anonymous> node_modules/vue/dist/vue.runtime.common.js:1811:12)
    at flushCallbacks (node_modules/vue/dist/vue.runtime.common.js:1732:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  message: 'expected false to be true',
  showDiff: true,
  actual: false,
  expected: true }
```


And what's even more weird - all tests are labeled as 'passed'

**Comment by eddyerburgh** [comment]
Thanks for the bug report. Can you create a new issue with a minimal reproduction @mrmnmly ?

**Comment by lukaszkups** [comment]
@eddyerburgh ok, created it here: https://github.com/vuejs/vue-test-utils/issues/371
