### ISSUE TITLE
SyntaxError: Unexpected token (1:1021), not working personally for one vue file

### ISSUE THREAD

**Issue by Nau077** [vuejs/vue-test-utils#1371]
### Version
1.0.0-beta.29

### Reproduction link
[https://codesandbox.io/s/hungry-curran-vg9j1](https://codesandbox.io/s/hungry-curran-vg9j1)

### Steps to reproduce
Probably write what versions of vue-test-utils, jest, vue-cli etc are 100% working with ech others

### What is expected?
Test for file leadCreate.vue starts like every others tests (all tests for vue components exepts this test start working, but this stop work since test read line with import leadCreate from '@/views/LeadCreate.vue'

### What is actually happening?
```
est suite failed to run    Jest encountered an unexpected token    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html    Details:    SyntaxError: Unexpected token (1:1021)      at Parser.pp$4.raise (node_modules/vue-template-es2015-compiler/buble.js:2757:13)
      at Parser.pp.unexpected (node_modules/vue-template-es2015-compiler/buble.js:647:8)
      at Parser.pp.expect (node_modules/vue-template-es2015-compiler/buble.js:641:26)
      at Parser.pp$2.parseBindingList (node_modules/vue-template-es2015-compiler/buble.js:1694:19)
      at Parser.pp$1.parseFunctionParams (node_modules/vue-template-es2015-compiler/buble.js:1231:22)
      at Parser.pp$1.parseFunction (node_modules/vue-template-es2015-compiler/buble.js:1218:8)
      at Parser.pp$3.parseExprAtom (node_modules/vue-template-es2015-compiler/buble.js:2184:17)
      at Parser.<anonymous> (node_modules/vue-template-es2015-compiler/buble.js:6004:24)
      at Parser.parseExprAtom (node_modules/vue-template-es2015-compiler/buble.js:6130:31)
      at Parser.pp$3.parseExprSubscripts (node_modules/vue-template-es2015-compiler/buble.js:2047:19)Test Suites: 1 failed, 3 passed, 4 total
Tests:       7 passed, 7 total
Snapshots:   0 total
Time:        2.506s
Ran all test suites.
SyntaxError: Unexpected token (1:1021)
    at Parser.pp$4.raise (/home/roma/prizma/mobilefront/node_modules/vue-template-es2015-compiler/buble.js:2757:13)
    at Parser.pp.unexpected (/home/roma/prizma/mobilefront/node_modules/vue-template-es2015-compiler/buble.js:647:8)
    at Parser.pp.expect (/home/roma/prizma/mobilefront/node_modules/vue-template-es2015-compiler/buble.js:641:26)
    at Parser.pp$2.parseBindingList (/home/roma/prizma/mobilefront/node_modules/vue-template-es2015-compiler/buble.js:1694:19)
    at Parser.pp$1.parseFunctionParams (/home/roma/prizma/mobilefront/node_modules/vue-template-es2015-compiler/buble.js:1231:22)
    at Parser.pp$1.parseFunction (/home/roma/prizma/mobilefront/node_modules/vue-template-es2015-compiler/buble.js:1218:8)
    at Parser.pp$3.parseExprAtom (/home/roma/prizma/mobilefront/node_modules/vue-template-es2015-compiler/buble.js:2184:17)
    at Parser.<anonymous> (/home/roma/prizma/mobilefront/node_modules/vue-template-es2015-compiler/buble.js:6004:24)
    at Parser.parseExprAtom (/home/roma/prizma/mobilefront/node_modules/vue-template-es2015-compiler/buble.js:6130:31)
    at Parser.pp$3.parseExprSubscripts (/home/roma/prizma/mobilefront/node_modules/vue-template-es2015-compiler/buble.js:2047:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! esuzb2b@0.2.0 test:unit: `vue-cli-service test:unit`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the esuzb2b@0.2.0 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.npm ERR! A complete log of this run can be found in:
npm ERR!     /home/roma/.npm/_logs/2019-12-13T12_59_08_078Z-debug.log
roma@roma-HP-ProDesk-400-G2-5-SFF:~/prizma/mobilefront$
```

---
I have jest.config.js like this : https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-unit-jest/presets/default/jest-preset.js (default preset)

package.json dev dependensies

    "@vue/cli-plugin-babel": "^3.11.0",
    "@vue/cli-plugin-eslint": "^3.11.0",
    "@vue/cli-plugin-unit-jest": "^4.0.5",
    "@vue/cli-service": "^3.11.0",
    "@vue/test-utils": "1.0.0-beta.29",
    "babel-eslint": "^10.0.1",

**Comment by afontcu** [comment]
Hi! Is `LeadCreate` importing a third-party component or similar? This is the relevant part of the error output:


```
This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

You'll find more details and examples of these config options in the docs: https://jestjs.io/docs/en/configuration.html
```

**Comment by Nau077** [comment]
Hi! Do you mean that some components were registrated like this way:
`
"/* eslint-disable */
import particles from './vue-particles.vue'

const VueParticles = {

    install (Vue, options) {
        Vue.component('vue-particles', particles)
    }

}

export default VueParticles"
`
?

**Comment by Nau077** [comment]
Unfortunately don`t fully understand  what do you meant by: "third-party component or similar".

**Comment by afontcu** [comment]
What I meant is that if you are importing third-party components from `node_modules` they might require some transformation:

"By default, if Jest sees a Babel config, it will use that to transform your files, ignoring 'node_modules'.". 
"To have some of your 'node_modules' files transformed, you can specify a custom 'transformIgnorePatterns' in your config."

Same thing if you are importing non-JS files:

"If you need a custom transformation specify a 'transform' option in your config."
"If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the 'moduleNameMapper' config option."


hope it helps!

**Comment by Nau077** [comment]
afontcu, I untderstand that I will need to tell Jest to compile some modules by whitelisting it in the transformIgnorePatterns option in my Jest config. But how can I figure out what accurate modules I need to add? 

If I saw something like: "Details:
    D:\project\node_modules\some_module\src\some_module\some_module.js:3
    import * as someLib from 'lib';" - it would be okey, all would be clear. After reading this error, I can fix it, and specify transformIgnorePatterns for this file.

But I get only: "Details:
    SyntaxError: Unexpected token (1:1021)". So how can I know what is file is problem?

**Comment by afontcu** [comment]
Looks like this is not related to Vue Test Utils itself, but to Jest and its transform capabilities. I would suggest trying to find the component/import statement that makes the build fail, so you can isolate it and decide how to transform it using Jest.
