### ISSUE TITLE
Cannot find module 'vue-template-compiler' from 'vue-test-utils.js'

### ISSUE THREAD

**Issue by sobolevn** [vuejs/vue-test-utils#1399]
### Version
1.0.0-beta.30

### Reproduction link
[https://github.com/wemake-services/wemake-vue-template](https://github.com/wemake-services/wemake-vue-template)

### Steps to reproduce
0. Create new project using this boilerplate
1. Install dependencies
2. Run `npm test`

### What is expected?
I expect everything to work as it was before the `-beta.30`

### What is actually happening?
Link to the failing CI: https://travis-ci.com/wemake-services/wemake-vue-template/builds/143178639
Now I have an exception:

```
> cross-env NODE_ENV=test jest

 FAIL  tests/components/action-bar.spec.ts
  ● Test suite failed to run

    Cannot find module 'vue-template-compiler' from 'vue-test-utils.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (node_modules/@vue/test-utils/dist/vue-test-utils.js:5:27)

 FAIL  tests/components/comment.spec.ts
  ● Test suite failed to run

    Cannot find module 'vue-template-compiler' from 'vue-test-utils.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (node_modules/@vue/test-utils/dist/vue-test-utils.js:5:27)

 FAIL  tests/pages/index.spec.ts
  ● Test suite failed to run

    Cannot find module 'vue-template-compiler' from 'vue-test-utils.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (node_modules/@vue/test-utils/dist/vue-test-utils.js:5:27)

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
Test Suites: 3 failed, 3 total
Tests:       0 total
Snapshots:   0 total
Time:        9.111s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! name@0.0.0 test:unit: `cross-env NODE_ENV=test jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the name@0.0.0 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sobolev/.npm/_logs/2020-01-09T13_49_48_645Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! name@0.0.0 test: `npm run test:engine && npm run test:unit && npm run lint`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the name@0.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sobolev/.npm/_logs/2020-01-09T13_49_48_684Z-debug.log
> cross-env NODE_ENV=test jest

 FAIL  tests/components/action-bar.spec.ts
  ● Test suite failed to run

    Cannot find module 'vue-template-compiler' from 'vue-test-utils.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (node_modules/@vue/test-utils/dist/vue-test-utils.js:5:27)

 FAIL  tests/components/comment.spec.ts
  ● Test suite failed to run

    Cannot find module 'vue-template-compiler' from 'vue-test-utils.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (node_modules/@vue/test-utils/dist/vue-test-utils.js:5:27)

 FAIL  tests/pages/index.spec.ts
  ● Test suite failed to run

    Cannot find module 'vue-template-compiler' from 'vue-test-utils.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (node_modules/@vue/test-utils/dist/vue-test-utils.js:5:27)

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
Test Suites: 3 failed, 3 total
Tests:       0 total
Snapshots:   0 total
Time:        9.111s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! name@0.0.0 test:unit: `cross-env NODE_ENV=test jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the name@0.0.0 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sobolev/.npm/_logs/2020-01-09T13_49_48_645Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! name@0.0.0 test: `npm run test:engine && npm run test:unit && npm run lint`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the name@0.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sobolev/.npm/_logs/2020-01-09T13_49_48_684Z-debug.log

```

---
- Jest config: https://github.com/wemake-services/wemake-vue-template/blob/master/template/jest.config.js
- package.json: https://github.com/wemake-services/wemake-vue-template/blob/master/template/package.json
- Actual tests: https://github.com/wemake-services/wemake-vue-template/tree/master/template/tests

**Comment by dobromir-hristov** [comment]
Check your lock file, is the template compiler there?

Its in the docs I guess. Probably a bad vesrsion match?
https://github.com/vuejs/vue-test-utils#peer-dependencies

**Comment by sobolevn** [comment]
After trying the same thing with `1.0.0-beta.29` I got slightly different result:

```
> cross-env NODE_ENV=test jest

 FAIL  tests/pages/index.spec.ts
  ● Test suite failed to run

    Cannot find module 'vue' from 'vue-test-utils.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (node_modules/@vue/test-utils/dist/vue-test-utils.js:5:27)

 FAIL  tests/components/action-bar.spec.ts
  ● Test suite failed to run

    Cannot find module 'vue' from 'vue-test-utils.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (node_modules/@vue/test-utils/dist/vue-test-utils.js:5:27)

 FAIL  tests/components/comment.spec.ts
  ● Test suite failed to run

    Cannot find module 'vue' from 'vue-test-utils.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (node_modules/@vue/test-utils/dist/vue-test-utils.js:5:27)

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
Test Suites: 3 failed, 3 total
Tests:       0 total
Snapshots:   0 total
Time:        8.865s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! name@0.0.0 test:unit: `cross-env NODE_ENV=test jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the name@0.0.0 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sobolev/.npm/_logs/2020-01-09T17_03_37_300Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! name@0.0.0 test: `npm run test:engine && npm run test:unit && npm run lint`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the name@0.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sobolev/.npm/_logs/2020-01-09T17_03_37_335Z-debug.log

```

Then I have tried to change `nuxt` version to `<2.11`. That's what happened: 

```

 PASS  tests/pages/index.spec.ts (13.827s)
  unit tests for Index view
    ✓ should have three comments (82ms)
    ✓ should load new comments on actions (38ms)
  snapshot test for Index view
    ✓ should match the snapshot (31ms)

 PASS  tests/components/comment.spec.ts (13.884s)
  unit tests for Comment component
    ✓ should have valid props (47ms)
    ✓ should have two buttons (36ms)
    ✓ should have correct values (14ms)
    ✓ should change rating: {"delta": 1, "styleName": "comment-positive"} (16ms)
    ✓ should change rating: {"delta": -1, "styleName": "comment-negative"} (8ms)
  snapshot tests for Comment component
    ✓ should match the snapshot (29ms)

-------------------------|----------|----------|----------|----------|----------------
---|
File                     |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line 
#s |
-------------------------|----------|----------|----------|----------|----------------
---|
All files                |    95.97 |    82.35 |       90 |    96.94 |                
   |
 components              |    95.45 |      100 |       80 |       95 |                   |
  ActionBar.vue          |      100 |      100 |      100 |      100 |                   |
  AppLogo.vue            |      100 |      100 |      100 |      100 |                   |
  Comment.vue            |    91.67 |      100 |       50 |    90.91 |                60 |
 logic                   |      100 |      100 |      100 |      100 |                   |
  store.ts               |      100 |      100 |      100 |      100 |                   |
  tokens.ts              |      100 |      100 |      100 |      100 |                   |
 logic/comments          |    95.12 |    77.78 |      100 |      100 |                   |
  models.ts              |      100 |      100 |      100 |      100 |                   |
  module.ts              |    94.87 |    77.78 |      100 |      100 |             50,56 |
 logic/comments/services |      100 |      100 |      100 |      100 |                   |
  api.ts                 |      100 |      100 |      100 |      100 |                   |
 mixins                  |      100 |      100 |      100 |      100 |                   |
  typed-store.ts         |      100 |      100 |      100 |      100 |                   |
 pages                   |    83.33 |      100 |       50 |    81.82 |                   |
  index.vue              |    83.33 |      100 |       50 |    81.82 |             56,57 |
 plugins                 |      100 |      100 |      100 |      100 |                   |
  type-di.ts             |      100 |      100 |      100 |      100 |                   |
 store                   |      100 |       50 |      100 |      100 |                   |
  index.ts               |      100 |       50 |      100 |      100 |                30 |
-------------------------|----------|----------|----------|----------|-------------------|
Test Suites: 3 passed, 3 total
Tests:       12 passed, 12 total
Snapshots:   3 passed, 3 total
Time:        15.902s
Ran all test suites.
  console.error node_modules/vue/dist/vue.runtime.common.dev.js:621
    [Vue warn]: The .native modifier for v-on is only valid on components but it was used on <button>.
    
    found in
    
    ---> <Comment>
           <Root>
```

So, it works for both `@vue/test-utils@1.0.0-beta.29` and `@vue/test-utils@1.0.0-beta.30` with `nuxt@2.10`, but does not work with `nuxt@2.11`. I guess it is some compatibility issue between these two tools. 

I will create a new issue for Nuxt bug tracker as well.

**Comment by dobromir-hristov** [comment]
To me this is just a dependency versioning issue.

**Comment by sobolevn** [comment]
It was related to `10` -> `12` node migration process: https://github.com/wemake-services/wemake-vue-template/compare/aedfddb452bf...1165ffb99cb8

Thanks!

**Comment by viT-1** [comment]
Why vue-template-compiler listed in peer dependencies?
I'm using vue components without .vue files (templates as strings in js) and I don't need in vue-template-compiler functionality for my project.
