### ISSUE TITLE
Breaks with Vue 3 alpha release

### ISSUE THREAD

**Issue by sonicoder86** [vuejs/vue-test-utils#1496]
### Version
1.0.0-beta.32

### Reproduction link
[https://github.com/blacksonic/todomvc-vue-composition-api](https://github.com/blacksonic/todomvc-vue-composition-api)

### Steps to reproduce
Clone the repository, install dependencies and run `npm run unit:test` which runs the Vue CLI's built-in test runner

### What is expected?
Run the unit tests

### What is actually happening?
Test run fails with error message when compiling.

RUNTIME EXCEPTION  Exception occurred while loading your tests

Error: 

Vue packages version mismatch:

- vue@3.0.0-alpha.11 (./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js)
- vue-template-compiler@2.6.11 (./node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

**Comment by sonicoder86** [comment]
Here is the stacktrace:

```
at Object../node_modules/vue-template-compiler/index.js (/Users/esysuser/workspace/todomvc-vue-composition-api/dist/js/webpack:/node_modules/vue-template-compiler/index.js:10:1)
    at __webpack_require__ (/Users/esysuser/workspace/todomvc-vue-composition-api/dist/js/webpack:/webpack/bootstrap:19:1)
    at Object../node_modules/@vue/test-utils/dist/vue-test-utils.js (/Users/esysuser/workspace/todomvc-vue-composition-api/dist/js/webpack:/node_modules/@vue/test-utils/dist/vue-test-utils.js:8:1)
    at __webpack_require__ (/Users/esysuser/workspace/todomvc-vue-composition-api/dist/js/webpack:/webpack/bootstrap:19:1)
    at Object../src/store/index.spec.js (/Users/esysuser/workspace/todomvc-vue-composition-api/dist/js/webpack:/src/store/index.spec.js:2:1)
    at __webpack_require__ (/Users/esysuser/workspace/todomvc-vue-composition-api/dist/js/webpack:/webpack/bootstrap:19:1)
    at run (/Users/esysuser/workspace/todomvc-vue-composition-api/dist/js/webpack:/node_modules/mochapack/lib/entry.js:3:1)
    at Array.forEach (<anonymous>)
    at Object../node_modules/mochapack/lib/entry.js (/Users/esysuser/workspace/todomvc-vue-composition-api/dist/js/webpack:/node_modules/mochapack/lib/entry.js:10:1)
    at __webpack_require__ (/Users/esysuser/workspace/todomvc-vue-composition-api/dist/js/webpack:/webpack/bootstrap:19:1)
    at ./node_modules/@babel/runtime/helpers/interopRequireDefault.js.module.exports (/Users/esysuser/workspace/todomvc-vue-composition-api/dist/js/webpack:/webpack/bootstrap:83:1)
    at Object.<anonymous> (/Users/esysuser/workspace/todomvc-vue-composition-api/dist/js/main.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object._module2.default._extensions.(anonymous function) [as .js] (/Users/esysuser/workspace/todomvc-vue-composition-api/node_modules/mochapack/src/util/registerRequireHook.js:99:12)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /Users/esysuser/workspace/todomvc-vue-composition-api/node_modules/mocha/lib/mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/esysuser/workspace/todomvc-vue-composition-api/node_modules/mocha/lib/mocha.js:331:14)
    at Mocha.run (/Users/esysuser/workspace/todomvc-vue-composition-api/node_modules/mocha/lib/mocha.js:809:10)
    at cb (/Users/esysuser/workspace/todomvc-vue-composition-api/node_modules/mochapack/src/runner/TestRunner.js:96:21)
    at /Users/esysuser/workspace/todomvc-vue-composition-api/node_modules/mochapack/src/webpack/compiler/registerReadyCallback.js:12:7
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/esysuser/workspace/todomvc-vue-composition-api/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:45:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/esysuser/workspace/todomvc-vue-composition-api/node_modules/tapable/lib/Hook.js:154:20)
    at emitRecords.err (/Users/esysuser/workspace/todomvc-vue-composition-api/node_modules/webpack/lib/Compiler.js:304:22)
    at Compiler.emitRecords (/Users/esysuser/workspace/todomvc-vue-composition-api/node_modules/webpack/lib/Compiler.js:499:39)
    at emitAssets.err (/Users/esysuser/workspace/todomvc-vue-composition-api/node_modules/webpack/lib/Compiler.js:298:10)
    at hooks.afterEmit.callAsync.err (/Users/esysuser/workspace/todomvc-vue-composition-api/node_modules/webpack/lib/Compiler.js:485:14)
    at _err0 (eval at create (/Users/esysuser/workspace/todomvc-vue-composition-api/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at compiler.hooks.afterEmit.tapAsync (/Users/esysuser/workspace/todomvc-vue-composition-api/node_modules/copy-webpack-plugin/dist/index.js:115:7)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/esysuser/workspace/todomvc-vue-composition-api/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/esysuser/workspace/todomvc-vue-composition-api/node_modules/tapable/lib/Hook.js:154:20)
    at asyncLib.forEachLimit.err (/Users/esysuser/workspace/todomvc-vue-composition-api/node_modules/webpack/lib/Compiler.js:482:27)
    at /Users/esysuser/workspace/todomvc-vue-composition-api/node_modules/neo-async/async.js:2818:7
    at done (/Users/esysuser/workspace/todomvc-vue-composition-api/node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/esysuser/workspace/todomvc-vue-composition-api/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at outputFileSystem.writeFile.err (/Users/esysuser/workspace/todomvc-vue-composition-api/node_modules/webpack/lib/Compiler.js:464:33)
    at MemoryFileSystem.writeFile (/Users/esysuser/workspace/todomvc-vue-composition-api/node_modules/memory-fs/lib/MemoryFileSystem.js:328:9)
    at writeOut (/Users/esysuser/workspace/todomvc-vue-composition-api/node_modules/webpack/lib/Compiler.js:462:30)
    at Immediate._onImmediate (/Users/esysuser/workspace/todomvc-vue-composition-api/node_modules/memory-fs/lib/MemoryFileSystem.js:288:4)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by dobromir-hristov** [comment]
Current version does not support vue 3

**Comment by sonicoder86** [comment]
Okay, I get it, but why do you close this issue?
Other components in the ecosystem like Vuex start to support it.

How can I help in making it work?

**Comment by dobromir-hristov** [comment]
We are writing a new package for Vue 3. This one will stay for Vue 2

**Comment by sonicoder86** [comment]
Thanks for the clarification 👍

Is it publicly available?

**Comment by dobromir-hristov** [comment]
Not yet

**Comment by sonicoder86** [comment]
Do you have an estimated release date? I'm curious to try it out.

**Comment by sonicoder86** [comment]
@dobromir-hristov the new 2.alpha release will be the one compatible with Vue 3?

**Comment by afontcu** [comment]
Hey! 👋Yes, we've been working on `v2` for VTU (alpha stage right now, obviously), and it is focused on supporting Vue 3. `v1` will remain to support Vue 2. It'll get out of alpha soon enough, too.

**Comment by sonicoder86** [comment]
@afontcu where is the development happening? i've migrated my test suite to the new syntax and found some bugs/missing features and would love to help. I haven't found any related commits/releases in this repository

**Comment by afontcu** [comment]
Hey! Sorry wasn't available. Looks like you already found the repo 🤗 thanks for contributing!
