### ISSUE TITLE
Mocking Parameterized Getter Results in TypeError

### ISSUE THREAD

**Issue by dev-talha-akbar** [vuejs/vue-test-utils#1616]
### Mocking Parameterized Getter Results in TypeError

I am writing a unit test for a component which uses Vuex. For the test, I am creating a mock store with a mocked parameterized getter which the components binds to an attribute in one of the components in the template. The dev build is compiled successfully and works expected in the browser but, not in the test environment. Here's what it throws:

> console.error node_modules/vue/dist/vue.runtime.common.dev.js:621
>       [Vue warn]: Error in render: "TypeError: Cannot read property '_modulesNamespaceMap' of undefined"
>       
>       found in
>       
>       ---> <Anonymous>
>              <Root>
>     console.error node_modules/vue/dist/vue.runtime.common.dev.js:1884
>       TypeError: Cannot read property '_modulesNamespaceMap' of undefined
>           at getModuleByNamespace (D:\Sites\assignment-papershift-cart-firebase-vue\node_modules\vuex\dist\vuex.common.js:1130:22)
>           at VueComponent.mappedGetter (D:\Sites\assignment-papershift-cart-firebase-vue\node_modules\vuex\dist\vuex.common.js:1017:25)

### Steps to reproduce

1. Create a component that mapGetters and binds parameterized getter to any attribute. In my case, I have `AppButtonCardAdd` component and binding to `disabled` attribute:

```vue
<template>
   <base-button :disabled="isProductInCart(productId)">
      <!-- ... -->
  </base-button>
</template>
```

2. Write a unit test that mocks that parameterized getter:

```javascript

it('is not disabled as product is not in cart'. () => {
   actions = {
      addProductToCart: jest.fn()
    };

    getters = {
      isProductInCart: () => () => {
        return false;
      }
    };

    store = new Vuex.Store({
      modules: {
        cart: {
          actions,
          getters,
          namespaced: true
        }
      }
    });

    wrapper = mount(AppButtonCartAdd, {
      localVue,
      store,
      propsData: {
        productId: "1"
      }
    });
});
```

### Expected behaviour

It should not throw TypeError. Instead, the test should pass with beautiful green output.

### Actual behaviour

It throws TypeError.

### Possible Solution

No idea. I need the getter to be parameterized.

**Comment by afontcu** [comment]
Hi, 

Can't run your test right now, but just in case – can you double check that you are injecting Vuex to `localVue`? `localVue.use(Vuex)`. your snippet is missing that bit, and the error seems related.

**Comment by dev-talha-akbar** [comment]
@afontcu Thanks for looking at it. I didn't include the complete file. Here's the complete file for reference. You can put that test in the original comment in it and check. By the way, I used parameterized getter in some other component and it worked fine. The only difference is of mount vs shallowMount.

```
import { mount, createLocalVue } from "@vue/test-utils";
import Vuex from "vuex";
import AppButtonCartAdd from "@/components/AppButtonCartAdd";
import BaseButton from "@/components/BaseButton";

const localVue = createLocalVue();

localVue.use(Vuex);
localVue.component("base-button", BaseButton);

let wrapper = null,
  store = null,
  getters = null,
  actions = null;

afterEach(() => {
  wrapper.destroy();
});

describe("AppButtonCartAdd.vue", () => {
  beforeEach(() => {
    actions = {
      addProductToCart: jest.fn()
    };

    getters = {
      isProductInCart: () => () => {
        return false;
      }
    };

    store = new Vuex.Store({
      modules: {
        cart: {
          actions,
          getters,
          namespaced: true
        }
      }
    });
  });

  it("renders the button", () => {
    wrapper = mount(AppButtonCartAdd, {
      localVue,
      propsData: {
        productId: "1"
      }
    });

    expect(wrapper.get("button"));
  });

  it("dispatches addProductToCart action on click", () => {
    wrapper = mount(AppButtonCartAdd, {
      localVue,
      store,
      propsData: {
        productId: "1"
      }
    });

    const button = wrapper.get("button");

    expect(actions.addProductToCart).toHaveBeenCalledTimes(0);

    button.trigger("click");

    expect(actions.addProductToCart).toHaveBeenCalled();
  });

  it("renders after slot content", () => {
    wrapper = mount(AppButtonCartAdd, {
      localVue,
      store,
      propsData: {
        productId: "1"
      },
      scopedSlots: {
        after: '<div class="add-after">Add After</div>'
      }
    });

    const afterContent = wrapper.get(".add-after");

    expect(afterContent.text()).toBe("Add After");
  });

  it("renders before slot content", () => {
    wrapper = mount(AppButtonCartAdd, {
      localVue,
      store,
      propsData: {
        productId: "1"
      },
      scopedSlots: {
        before: '<div class="add-before">Add Before</div>'
      }
    });

    const beforeContent = wrapper.get(".add-before");

    expect(beforeContent.text()).toBe("Add Before");
  });
});

// TODO: Add tests for disabled prop based on isProductInCart getter
// See https://github.com/vuejs/vue-test-utils/issues/1616

```

**Comment by dev-talha-akbar** [comment]
@afontcu Here's the complete file:

```javascript
import { mount, createLocalVue } from "@vue/test-utils";
import Vuex from "vuex";
import AppButtonCartAdd from "@/components/AppButtonCartAdd";
import BaseButton from "@/components/BaseButton";

const localVue = createLocalVue();

localVue.use(Vuex);
localVue.component("base-button", BaseButton);

let wrapper = null,
  store = null,
  getters = null,
  actions = null;

afterEach(() => {
  wrapper.destroy();
});

describe("AppButtonCartAdd.vue", () => {
  beforeEach(() => {
    actions = {
      addProductToCart: jest.fn()
    };

    getters = {
      isProductInCart: () => () => {
        return false;
      }
    };

    store = new Vuex.Store({
      modules: {
        cart: {
          actions,
          getters,
          namespaced: true
        }
      }
    });
  });

  it("renders the button", () => {
    wrapper = mount(AppButtonCartAdd, {
      localVue,
      propsData: {
        productId: "1"
      }
    });

    expect(wrapper.get("button"));
  });

  it("dispatches addProductToCart action on click", () => {
    wrapper = mount(AppButtonCartAdd, {
      localVue,
      store,
      propsData: {
        productId: "1"
      }
    });

    const button = wrapper.get("button");

    expect(actions.addProductToCart).toHaveBeenCalledTimes(0);

    button.trigger("click");

    expect(actions.addProductToCart).toHaveBeenCalled();
  });

  it("renders after slot content", () => {
    wrapper = mount(AppButtonCartAdd, {
      localVue,
      store,
      propsData: {
        productId: "1"
      },
      scopedSlots: {
        after: '<div class="add-after">Add After</div>'
      }
    });

    const afterContent = wrapper.get(".add-after");

    expect(afterContent.text()).toBe("Add After");
  });

  it("renders before slot content", () => {
    wrapper = mount(AppButtonCartAdd, {
      localVue,
      store,
      propsData: {
        productId: "1"
      },
      scopedSlots: {
        before: '<div class="add-before">Add Before</div>'
      }
    });

    const beforeContent = wrapper.get(".add-before");

    expect(beforeContent.text()).toBe("Add Before");
  });
});

describe("AppButtonCartAdd.vue without product in cart", () => {
  beforeEach(() => {
    actions = {
      addProductToCart: jest.fn()
    };

    getters = {
      isProductInCart: () => () => {
        return false;
      }
    };

    store = new Vuex.Store({
      modules: {
        cart: {
          actions,
          getters,
          namespaced: true
        }
      }
    });
  });

  it("is not disabled as the product is not in cart", () => {
    wrapper = mount(AppButtonCartAdd, {
      localVue,
      store,
      propsData: {
        productId: "1"
      }
    });

    const button = wrapper.get("button");

    expect(button.element.disabled).toBe(false);
  });
});

describe("AppButtonCartAdd.vue with product in cart", () => {
  beforeEach(() => {
    actions = {
      addProductToCart: jest.fn()
    };

    getters = {
      isProductInCart: () => () => {
        return true;
      }
    };

    store = new Vuex.Store({
      modules: {
        cart: {
          actions,
          getters,
          namespaced: true
        }
      }
    });
  });

  it("is disabled as the product is in cart", () => {
    wrapper = mount(AppButtonCartAdd, {
      localVue,
      store,
      propsData: {
        productId: "1"
      }
    });

    const button = wrapper.get("button");

    expect(button.element.disabled).toBe(true);
  });
});

```

**Comment by dev-talha-akbar** [comment]
I found the issue. The stack trace actually lead me to the actual test case for which the TypeError was being thrown. In that test case, I missed passing the `store` object and hence that error. This is not a bug on `vue-test-utils`.

@afontcu Thanks for looking at it anyway.
