### ISSUE TITLE
Cannot access properties in scoped-slots with a Renderless component

### ISSUE THREAD

**Issue by sebj54** [vuejs/vue-test-utils#1686]
### Subject of the issue

I am using a renderless component in a project and wanted to add a test on it but I can't access scoped properties  (undefined).

### Steps to reproduce

Renderless component: 

```vue
<!-- Renderless.vue -->
<script>
export default {
    data() {
        return {
            fields: {
                name: 'abcd',
                email: 'abcd@example.com',
            },
        }
    },
    render() {
        return this.$scopedSlots.default({
            fields: this.fields,
        })
    },
}
</script>
```

Component which implements Renderless component:

```vue
<!-- ImplementsRenderless.vue -->
<template>
    <renderless v-slot="{ fields }">
        <div>{{ fields.name }}</div>
    </renderless>
</template>

<script>
import Renderless from '../components/Renderless'

export default {
    components: {
        Renderless,
    },
}
</script>
```

Test:

```js
import { shallowMount } from '@vue/test-utils'
import ImplementsRenderless from '../components/ImplementsRenderless'

const wrapper = shallowMount(ImplementsRenderless)

describe('ContactForm', () => {
    it('renders', () => {
        expect(wrapper.find('div').exists()).toBe(true)
    })

    it('uses scoped properties', () => {
        expect(wrapper.find('div').text()).toBe('abcd')
    })
})
```

### Expected behaviour

Test should pass.

### Actual behaviour

Test fails with an error. It seems that `fields.name` in `ImplementsRenderless.vue` is not accessible because `fields` is not defined.

```
 FAIL  tests/unit/renderless.spec.js
  ● Test suite failed to run

    TypeError: Cannot read property 'name' of undefined



      at Object.fn [as default] (tests/components/ImplementsRenderless.vue:29:40)
      at node_modules/@vue/test-utils/dist/vue-test-utils.js:2371:125
          at Array.map (<anonymous>)
      at Proxy.render (node_modules/@vue/test-utils/dist/vue-test-utils.js:2371:50)
      at VueComponent.Vue._render (node_modules/vue/dist/vue.runtime.common.dev.js:3538:22)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4054:21)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:4454:12)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4061:3)
      at VueComponent.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8392:10)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:3112:13)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:5958:9)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:5905:9)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6455:7)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3933:19)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4054:10)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:4454:12)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4061:3)
      at VueComponent.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8392:10)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:3112:13)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:5958:9)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:5905:9)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6455:7)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3933:19)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4054:10)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:4454:12)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4061:3)
      at VueComponent.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8392:10)
      at mount (node_modules/@vue/test-utils/dist/vue-test-utils.js:13935:21)
      at shallowMount (node_modules/@vue/test-utils/dist/vue-test-utils.js:13961:10)
      at Object.<anonymous> (tests/unit/renderless.spec.js:4:17)
```

### Possible Solution

🤷‍♂️

**Comment by afontcu** [comment]
Hi! Don't have the time to dig in right now, but using `mount` instead of `shallowMount` should fix the issue. 

That being said, I agree VTU shouldn't fail that hard given that scenario, so this is something worth looking into.

**Comment by sebj54** [comment]
Thanks for your quick feedback! 

You're right, it works as it should with `mount`. I didn't know the difference between `mount` and `shallowMount`, thanks for the heads up!

**Comment by CodeDredd** [comment]
I would say this is normal behaviour.
@sebj54 : The difference between `mount` and `shallowMount` is, that `mount` is resolving and importing all components in your component.
For `shallowMount` to work with childcomponents you need to mock them or import them in the test.Then define them in the options, because `shallowMount` is only stubbing the child components. -> see https://vue-test-utils.vuejs.org/api/#mount 

A good explanation is also here: https://coderethinked.com/shallowmount-vs-mount-in-vue-test-utils-with-an-example/

Maybe a check for `shallowMount` can be implemented, so warning comes if `shallowMount` is used for a component with child components, where the child components are not mocked.

**Comment by sebj54** [comment]
A week after, I'd say the same thing: it fails as expected. At the time of posting, it wasn't that expected to me as I don't usually deal with tests nor renderless components.

Your idea is great to show a warning though! It would help newbies like me if it suggests to use `mount` instead or mock child components.
