### ISSUE TITLE
Template-based functional components arent working

### ISSUE THREAD

**Issue by pimlie** [vuejs/vue-test-utils#1755]
### Subject of the issue

See issue title, for convenience here is a quick link to the [Vue2 docs](https://vuejs.org/v2/guide/render-function.html#Functional-Components).

Btw, Im aware that template-based functional components arent supported by Vue3, Im hoping its a 'quick' fix though because it will take some time to move everything from v2 to v3 :)

### Steps to reproduce

```js
// TestComponent.vue
<template functional>
  <div :class="props.aClass">Hello</div>
</template>

<script>
export default {
  props: {
    aClass: {
      type: String,
      default: 'text-green'
    }
  }
}
</script>

// vtu.test.js
import { mount } from '@vue/test-utils'
import TestComponent from './TestComponent'

test('render functional component', () => {
  const wrapper = mount(TestComponent)
  expect(wrapper.html()).toBe('<div class="text-green">Hello</div>')
})
```

### Expected behaviour

The test should pass

### Actual behaviour

The test fails with:
```
 console.error
    TypeError: Cannot read property 'aClass' of undefined
        at Proxy.render (test/TestComponent.vue:27:22)
        at VueComponent.Vue._render (node_modules/vue/dist/vue.runtime.common.dev.js:3538:22
```
### Possible Solution

A functional component with a render function does work, but it seems that VTU currently only checks for the `functional` prop on a component and doesnt understand the functional attribute of the template.

### More info

Adding a prop `functional: true` in the script part of the SFC doesnt work either, then you will get the error
```js
TypeError: Cannot read property '$createElement' of null
```

Also, if you pass a (functional) context to mount then VTU will log the error:
```js
[vue-test-utils]: mount.context can only be used when mounting a functional component
```

**Comment by pimlie** [comment]
This might be a Vue / Vue-compiler issue actually. The compiled render function with a template based functional component looks like:

```js
    function render() {
      var _vm = this;
    
      var _h = _vm.$createElement;
    
      var _c = _vm._self._c || _h;
    
      return _c('div', {
        class: _vm.props.aClass
      }, [_vm._v("Hello")]);
    }
```

which triggers the TypeError about $createElement because there is no `this`
