### ISSUE TITLE
Can't mount components in version 2.0.0-rc3

### ISSUE THREAD

**Issue by manuelmazzuola** [vuejs/vue-test-utils#1802]
Bumping @vue/test-utils from `2.0.0-rc.1` to `2.0.0-rc.3` I get that issue
vue version 3.0.5

```
● icon › should render the bell icon

    TypeError: 'set' on proxy: trap returned falsish for property 'hasOwnProperty'

       6 |     expect.assertions(1);
       7 | 
    >  8 |     const wrapper = mount(Icon, {
         |                     ^
       9 |       props: {
      10 |         name: 'bell',
      11 |       },

      at mount (node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:2348:24)
      at Object.<anonymous> (tests/unit/specs/components/icon.spec.ts:8:21)
```

**Comment by cristianbenites** [comment]
Hey, I'm exactly with the same issue.
Have you figured out how to fix it?
