### ISSUE TITLE
Receiving TypeError when testing components while following upgrade guide to Vue 3

### ISSUE THREAD

**Issue by jskitz** [vuejs/vue-test-utils#1887]
### Subject of the issue

I am performing the steps of doing a migration build from Vue 2 to Vue 3. I noticed that none of my component tests are working any longer as I try to do the migration. Just to make sure that it wasn't my components, I copied `HelloWorld.vue` and `example.spec.js` from `vue create new-project-name`. The error that I'm getting is:

`TypeError: Right-hand side of 'instanceof' is not an object`

### Steps to reproduce

I've been attempting to upgrade my Vue 2 project to Vue 3 using the [Migration Build guidelines](https://v3.vuejs.org/guide/migration/migration-build.html#overview)

Additionally, I upgraded to `"@vue/test-utils": "^2.0.0-0"` and `"vue-jest": "^5.0.0-0",`

This was in response to other issues that I was having before these were installed, where the tests were complaining about a version mismatch on `vue-template-compiler`. The module `vue-template-compiler` was uninstalled as part of the migration steps.

### Expected behaviour

I would expect that the HelloWorld.vue sample test should work in my environment.

### Actual behaviour

I'm getting this error with the following stack trace:

`TypeError: Right-hand side of 'instanceof' is not an object`

Here is the stack trace:

```
  FAIL  tests/unit/components/example.spec.js
  ● HelloWorld.vue › renders props.msg when passed

    TypeError: Right-hand side of 'instanceof' is not an object

       5 |   it('renders props.msg when passed', () => {
       6 |     const msg = 'new message'
    >  7 |     const wrapper = shallowMount(HelloWorld, {
         |                     ^
       8 |       props: { msg }
       9 |     })
      10 |     expect(wrapper.text()).toMatch(msg)

      at normalizeContainer (node_modules/@vue/runtime-dom/dist/runtime-dom.cjs.js:1375:19)
      at Object.app.mount (node_modules/@vue/runtime-dom/dist/runtime-dom.cjs.js:1290:27)
      at mount (node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:7826:18)
      at shallowMount (node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:7845:12)
      at Object.<anonymous> (tests/unit/components/example.spec.js:7:21)
```

### Possible Solution

When looking at the line of code where this fails, I see that it is testing if the container is an instance of window.ShadowRoot in normalizeContainer in the file `@vue/runtime-dom.cjs.js`.

```
    if (container instanceof window.ShadowRoot
```

Since `window` is a browser global, I'm just wondering if this is properly defined in my testing environment or how to do this correctly? I'm not exactly sure what else to try except for trying to get my environment as close to what vue-cli produces for a brand new project. The project I'm working on has been continuously upgraded for the last 3 years, and I really want to get on Vue 3 before building a bunch of new stuff this coming year. Thanks in advance for any help.

**Comment by jskitz** [comment]
After a lot of configuration trials and tests, I changed my `jest.config.js` to what vue-cli currently creates. Most of what was in the preset already had been in my `jest.config.js` file, but there must be something different between the two setups. The main line that fixed my tests was this one

```
module.exports = {
  preset: '@vue/cli-plugin-unit-jest',
  ...
```
After adding that, and removing all of the duplicate definitions between the preset and what I had defined in my local file, I added back my specific changes such as a some setupFiles, and coverage reports. Then it magically started working. Tests are passing!

If you have an old jest.config.js with most of what was in the preset defined you could potentially run into this issue. Closing but hopefully this helps others if you run across something similar with the migration steps.
