### ISSUE TITLE
TypeError: Cannot set property 'productionTip' of undefined

### ISSUE THREAD

**Issue by misyaath** [vuejs/vue-test-utils#1902]
When Work with @vue/test-utils with vue 3.0 its return error when run test 

` RUNTIME EXCEPTION  Exception occurred while loading your tests

TypeError: Cannot set property 'productionTip' of undefined
    at Object.<anonymous> (/var/www/html/vue-tdd/.tmp/mochapack/1630481243271/main.js:20:24023)
    at Object.<anonymous> (/var/www/html/vue-tdd/.tmp/mochapack/1630481243271/main.js:20:25006)
    at n (/var/www/html/vue-tdd/.tmp/mochapack/1630481243271/main.js:1:110)
    at Module.<anonymous> (/var/www/html/vue-tdd/.tmp/mochapack/1630481243271/main.js:20:239428)
    at n (/var/www/html/vue-tdd/.tmp/mochapack/1630481243271/main.js:1:110)
    at /var/www/html/vue-tdd/.tmp/mochapack/1630481243271/main.js:1:8878
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/var/www/html/vue-tdd/.tmp/mochapack/1630481243271/main.js:1:8857)
    at Object.<anonymous> (/var/www/html/vue-tdd/.tmp/mochapack/1630481243271/main.js:1:8888)
    at n (/var/www/html/vue-tdd/.tmp/mochapack/1630481243271/main.js:1:110)
    at /var/www/html/vue-tdd/.tmp/mochapack/1630481243271/main.js:1:953
    at Object.<anonymous> (/var/www/html/vue-tdd/.tmp/mochapack/1630481243271/main.js:1:962)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.module_1.default._extensions.<computed> [as .js] (/var/www/html/vue-tdd/node_modules/mochapack/src/util/registerRequireHook.ts:106:12)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)`

**Comment by mrRajopadhyaya** [comment]
Is there any update regarding this issue? I'm facing this problem while upgrading vue 2 app to vue 3

**Comment by misyaath** [comment]
config.productionTip Removed in vue 3
[#](https://v3-migration.vuejs.org/breaking-changes/global-api.html#config-productiontip-removed)

In Vue 3.x, the "use production build" tip will only show up when using the "dev + full build" (the build that includes the runtime compiler and has warnings).

For ES modules builds, since they are used with bundlers, and in most cases a CLI or boilerplate would have configured the production env properly, this tip will no longer show up.

[Migration build flag: CONFIG_PRODUCTION_TIP](https://v3-migration.vuejs.org/migration-build.html#compat-configuration)

Read Further https://v3-migration.vuejs.org/breaking-changes/global-api.html#config-productiontip-removed

**Comment by ebisbe** [comment]
@misyaath your answers resolves the issue, right?

**Comment by ebisbe** [comment]
Also this is not the repository for vue 3. You need to go https://github.com/vuejs/test-utils
