### ISSUE TITLE
Vue-test-utils seems to use typescript while i don't want to use it?

### ISSUE THREAD

**Issue by DanielvdSpoel** [vuejs/vue-test-utils#1911]
### Steps to reproduce
- Install a fresh ionic project
- Remove all typescript stuff
- Unable to run unit tests
Tell us how to reproduce this issue. Please provide a working and simplified example.

### Expected behaviour

Unit test to run

### Actual behaviour

Fail with this error:
npm run test:unit

> fiets-toch@0.0.1 test:unit C:\Users\USER\Documents\MediaMere\fiets-app
> vue-cli-service test:unit

 FAIL  tests/unit/example.spec.js
  ● Test suite failed to run

    Unable to load the module "typescript". Using "ts-jest" requires this package to be installed. To fix it:
        ↳ install "typescript": `npm i -D typescript` (or `yarn add --dev typescript`)

      at Importer._import (node_modules/ts-jest/dist/util/importer.js:143:15)
      at Importer.typescript (node_modules/ts-jest/dist/util/importer.js:74:21)
      at ConfigSet.get (node_modules/ts-jest/dist/config/config-set.js:384:40)
      at ConfigSet.compilerModule (node_modules/ts-jest/dist/util/memoize.js:43:24)
      at ConfigSet.readTsConfig (node_modules/ts-jest/dist/config/config-set.js:625:23)
      at ConfigSet.get (node_modules/ts-jest/dist/config/config-set.js:313:31)
      at ConfigSet._typescript (node_modules/ts-jest/dist/util/memoize.js:43:24)
      at ConfigSet.get [as typescript] (node_modules/ts-jest/dist/config/config-set.js:283:25)
      at getTsJestConfig (node_modules/vue-jest/lib/utils.js:80:30)
      at processTemplate (node_modules/vue-jest/lib/process.js:102:20)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        5.629s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fiets-toch@0.0.1 test:unit: `vue-cli-service test:unit`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fiets-toch@0.0.1 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USER\AppData\Roaming\npm-cache\_logs\2021-10-12T08_20_37_464Z-debug.log

### Possible Solution

There propaly is one, just haven't found it yet!

**Comment by bponomarenko** [comment]
Hi @DanielvdSpoel, I was just exploring some other issues to see if they are related to mine... But from your description I'm not sure this repo is the right place to post your question. I'm using `@vue/test-utils` in a Javacript project (no TypeScript at all), and it works fine.

From your description it seems that issue may be either in the ionic framework or in the "Remove all typescript stuff" step, as something is still configured to use typescript.

**Comment by ebisbe** [comment]
If you want some further inspection @DanielvdSpoel provide a reproduction but as stated by bponomarenko this is not likely related to this repo itself.
