### ISSUE TITLE
How to properly mock ResizeObserver?

### ISSUE THREAD

**Issue by ozyx** [vuejs/vue-test-utils#1916]
Hi everyone,

I am using `vue` v2.6.11 and `vue-test-utils` v1.2.2

I have a component `DisclaimerModal` that registers a `ResizeObserver` within the `$nextTick()` callback in `mounted()` as such:

```js
  mounted() {
    this.$nextTick(function() {
      const element = this.$refs.disclaimerContent
      if (!element) { return }

      // Handle the case if disclaimerContent overflows due to window resize
      this.ro = new ResizeObserver(this.onResize).observe(this.$refs.disclaimerContent)
      this.calcIsOverflowing()
    })
  },
```

My test:
```js
  let wrapper

  beforeEach(() => {
    wrapper = shallowMount(DisclaimerModal, {
      mocks: {
        $store
      }
    })
  })

  it('button is disabled if overflowing and not scrolled to bottom', async() => {
    await wrapper.setData({
      isOverflowing: true,
      scrolledToBottom: false
    })

    const button = wrapper.find('#agreeButton')

    expect(button.attributes('disabled')).to.equal('true')
  })
```

But when I run the test, I get warnings from Vue:

```
ReferenceError: ResizeObserver is not defined
    at VueComponent.<anonymous> (.../DisclaimerModal.vue:85:1)
    at Array.<anonymous> (.../webpack:/node_modules/vue/dist/vue.runtime.esm.js:1980:1)
    at flushCallbacks (.../webpack:/node_modules/vue/dist/vue.runtime.esm.js:1906:1)
```

I can mock ResizeObserver as such:

```js
class ResizeObserver {
  observe() {
    // do nothing
  }
  unobserve() {
    // do nothing
  }
}
```

...but passing this as part of the `mocks` object during `shallowMount()` doesn't seem to fix the warning. I've also tried setting `window.ResizeObserver = ResizeObserver` in different scopes but to no avail. This isn't breaking my tests, but it is a bit annoying to see the warning over and over again in the output.

Hope I explained the issue well enough. Any information you could provide would be of great help. 
Thanks for all your hard work!

**Comment by ozyx** [comment]
Hi again,

Fixed my own issue!

I was able to mock `ResizeObserver` by registering it in the nodeJS global scope above my tests:

```js
  // Mock object for ResizeObserver
  class ResizeObserver {
    observe() {
      // do nothing
    }
    unobserve() {
      // do nothing
    }
  }

  // Register mock ResizeObserver in NodeJS global scope
  global.ResizeObserver = ResizeObserver
```

This resolved the warnings.

**Comment by EmilyRagan** [comment]
Another option is

```ts
import { vi } from 'vitest'

global.ResizeObserver = vi.fn(() => {
  return {
    disconnect: vi.fn(),
    observe: vi.fn(),
    unobserve: vi.fn()
  }
})
```
