### ISSUE TITLE
Jest failed Unexpected token } in JSON at position 441 Vue2 Typescript

### ISSUE THREAD

**Issue by srbastian23** [vuejs/vue-test-utils#1954]
### Version
1.3.0

### Reproduction link
[github.com](https://github.com/srbastian23/jest-vue2)

### Steps to reproduce

run yarn test.

### What is expected?
run correctly the test

### What is actually happening?
Shows the next error: 
```
 Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    SyntaxError: Unexpected token } in JSON at position 441
        at JSON.parse (<anonymous>)

      at parse (node_modules/tsconfig/src/tsconfig.ts:195:15)
      at readFileSync (node_modules/tsconfig/src/tsconfig.ts:181:10)
      at Object.loadSync (node_modules/tsconfig/src/tsconfig.ts:151:18)
      at find (node_modules/vue-jest/lib/load-typescript-config.js:33:39)
      at loadTypescriptConfig (node_modules/vue-jest/lib/load-typescript-config.js:73:26)
      at compileTypescript (node_modules/vue-jest/lib/compilers/typescript-compiler.js:9:20)
      at processScript (node_modules/vue-jest/lib/process.js:23:12)
      at Object.module.exports [as process] (node_modules/vue-jest/lib/process.js:42:18)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:620:31)

```

**Comment by srbastian23** [comment]
This is my jest.config.js

``` // Sync object
/** @type {import('@jest/types').Config.InitialOptions} */
const config = {
  verbose: true,
}

module.exports = config

// Or async function
module.exports = async () => {
  return {
    // preset: '@vue/cli-plugin-unit-jest',
    verbose: true,
    moduleFileExtensions: [
      'js',
      'ts',
      'json',
      'vue',
    ],
    transform: {
      '.*\\.(vue)$': 'vue-jest',
      '^.+\\.tsx?$': 'ts-jest',
    },
    testURL: 'http://localhost/',
    testRegex: '(/__tests__/.*|(\\.|/)(test|spec))\\.(jsx?|tsx?)$',
    testEnvironment: 'jsdom',
    preset: 'ts-jest/presets/js-with-ts',
    snapshotSerializers: [
      'jest-serializer-vue',
    ],
  }
}

**Comment by yesiddg** [comment]
Add to the jest.config.js

transformIgnorePatterns: ['/node_modules/(?!library-with-problems)']

**Comment by amitleuva1987** [comment]
> Add to the jest.config.js
> 
> transformIgnorePatterns: ['/node_modules/(?!library-with-problems)']

This doesn't work. I am facing the same issue.

**Comment by amitleuva1987** [comment]
@srbastian23 , did you get any solution for this issue?

**Comment by amitleuva1987** [comment]
Hey @srbastian23 ,

Here is the solution (https://github.com/vuejs/vue-cli/issues/2000) . Ping me back if it doesn't work for you.

**Comment by 1baga** [comment]
if you have a trailing comma anywhere in your ts-config file do take it off.. that was what fixed my problem..

**Comment by Paula2001** [comment]
> if you have a trailing comma anywhere in your ts-config file do take it off.. that was what fixed my problem..

mine too thanks

**Comment by ebisbe** [comment]
Closing since it's not related to the repository.
