### ISSUE TITLE
ReferenceError: defineProps is not defined when run test

### ISSUE THREAD

**Issue by ningrunting** [vuejs/vue-test-utils#1967]
```
<template>
  <div class="home">
    <header>
      <h1>home page {{ props.name }}</h1>
    </header>
  </div>
</template>
<script lang="ts" setup>
import { defineProps, withDefaults } from 'vue'
const props = withDefaults(defineProps<{ name: string }>(), { name: 'test' })
</script>
```
```
it('renders home page when passed', () => {
    const msg = 'home page test'
    const wrapper = shallowMount(Home)
    expect(wrapper.text()).toMatch(msg)
  })
```
### Subject of the issue
add unit test for vue3 setup component but got the error:
if I remove defineProps, it passed, If added won't
```
ReferenceError: defineProps is not defined

at setup (/vue3-test-practice/src/spike/Home.vue:10:15)
at callWithErrorHandling (/vue3-test-practice/node_modules/.pnpm/@vue+runtime-core@3.2.26/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6650:22)
at setupStatefulComponent (/vue3-test-practice/node_modules/.pnpm/@vue+runtime-core@3.2.26/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6276:29)
at setupComponent (/vue3-test-practice/node_modules/.pnpm/@vue+runtime-core@3.2.26/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6232:11)
at mountComponent (/vue3-test-practice/node_modules/.pnpm/@vue+runtime-core@3.2.26/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4166:13)
at processComponent (/vue3-test-practice/node_modules/.pnpm/@vue+runtime-core@3.2.26/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4141:17)
at patch (/vue3-test-practice/node_modules/.pnpm/@vue+runtime-core@3.2.26/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3744:21)
at ReactiveEffect.componentUpdateFn [as fn] (/vue3-test-practice/node_modules/.pnpm/@vue+runtime-core@3.2.26/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4281:21)
at ReactiveEffect.run (/vue3-test-practice/node_modules/.pnpm/@vue+reactivity@3.2.26/node_modules/@vue/reactivity/dist/reactivity.cjs.js:164:29)
at setupRenderEffect (/vue3-test-practice/node_modules/.pnpm/@vue+runtime-core@3.2.26/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4400:9)
at mountComponent (/vue3-test-practice/node_modules/.pnpm/@vue+runtime-core@3.2.26/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4183:9)
at processComponent (/vue3-test-practice/node_modules/.pnpm/@vue+runtime-core@3.2.26/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4141:17)
at patch (/vue3-test-practice/node_modules/.pnpm/@vue+runtime-core@3.2.26/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3744:21)
at render (/vue3-test-practice/node_modules/.pnpm/@vue+runtime-core@3.2.26/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4885:13)
at mount (/vue3-test-practice/node_modules/.pnpm/@vue+runtime-core@3.2.26/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3167:25)
at Object.app.mount (/vue3-test-practice/node_modules/.pnpm/@vue+runtime-dom@3.2.26/node_modules/@vue/runtime-dom/dist/runtime-dom.cjs.js:1530:23)
at mount (/vue3-test-practice/node_modules/.pnpm/@vue+test-utils@2.0.0-rc.17_vue@3.2.26/node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:7919:18)
at shallowMount (/vue3-test-practice/node_modules/.pnpm/@vue+test-utils@2.0.0-rc.17_vue@3.2.26/node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:7934:12)
at Object.<anonymous> (/vue3-test-practice/tests/unit/example.spec.ts:7:21)
at Object.asyncJestTest (/vue3-test-practice/node_modules/.pnpm/registry.npmmirror.com+jest-jasmine2@24.9.0/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)
at /vue3-test-practice/node_modules/.pnpm/registry.npmmirror.com+jest-jasmine2@24.9.0/node_modules/jest-jasmine2/build/queueRunner.js:43:12
at new Promise (<anonymous>)
at mapper (/vue3-test-practice/node_modules/.pnpm/registry.npmmirror.com+jest-jasmine2@24.9.0/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
at /vue3-test-practice/node_modules/.pnpm/registry.npmmirror.com+jest-jasmine2@24.9.0/node_modules/jest-jasmine2/build/queueRunner.js:73:41
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

versions:
"vue": "3.2.26",
"@testing-library/jest-dom": "^4.2.4",
"@testing-library/vue": "^5.8.2",
"@vue/test-utils": "v2.0.0-rc.17",
"vue-jest": "5.0.0-alpha.10",

**Comment by lmiller1990** [comment]
Seems a config issue, please post a repo (not just deps). It's too hard to recreate from this.

**Comment by HassanAlgoz** [comment]
Same issue. Here is my vite.config.js

```
export default defineConfig({
  plugins: [vue()],
  ...
  test: {
    globals: true,
    environment: 'happy-dom',
  }
})
```

And my component:

```vue
<script setup>
const props = defineProps({
  count: Number,
  pageSize: {
    type: Number,
    default: 10,
  }
});
</script>

<template>
    ...
</template>
```

**Comment by lmiller1990** [comment]
Can you provide a minimal reproduction? I've got a large code base with Vite, defineProps, etc etc and it's working fine. It's likely a config error, I'll need to see a reproduction to help, though.

**Comment by ebisbe** [comment]
@lmiller1990 Shouldn't this issue be on the Vue-test-utils v2 repository?

**Comment by lmiller1990** [comment]
Yes it should, good point.

I also don't think there's a bug - `defineProps` is a compiler macro, according to the RFC - you don't need to import it, it's injected globally.
