### ISSUE TITLE
vue-router not installed error

### ISSUE THREAD

**Issue by anandrikka** [vuejs/vue-test-utils#353]
I followed the same steps mentioned in documentation, but getting following error
`
Error: [vue-router] not installed. Make sure to call `Vue.use(VueRouter)` before creating root instance.
	    at assert (webpack:///node_modules/vue-router/dist/vue-router.esm.js:10:0 <- index.js:16838:11)
	    at VueRouter.init (webpack:///node_modules/vue-router/dist/vue-router.esm.js:2476:0 <- index.js:19304:46)
	    at VueComponent.beforeCreate (webpack:///node_modules/vue-router/dist/vue-router.esm.js:540:0 <- index.js:17368:22)
	    at callHook (webpack:///node_modules/vue/dist/vue.esm.js:2895:0 <- index.js:5294:21)
	    at VueComponent.Vue._init (webpack:///node_modules/vue/dist/vue.esm.js:4556:0 <- index.js:6955:5)
	    at new VueComponent (webpack:///node_modules/vue/dist/vue.esm.js:4728:0 <- index.js:7127:12)
	    at createConstructor (webpack:///node_modules/vue-test-utils/dist/vue-test-utils.js:4366:0 <- index.js:51028:12)
	    at mount (webpack:///node_modules/vue-test-utils/dist/vue-test-utils.js:4446:0 <- index.js:51108:12)
	    at Context.<anonymous> (webpack:///test/unit/specs/components/App.spec.js:15:18 <- index.js:46638:41)
`

**Comment by kellym** [comment]
I got this same error while testing. Did you ever find a solution?

**Comment by kellym** [comment]
Added a "valid" issue with steps to reproduce. Temporary solution there, too:
https://github.com/vuejs/vue-test-utils/issues/406

**Comment by anandrikka** [comment]
@kellym Yes, I made a mistake of keeping `Vue.use(xxxx)` inside my router file. I'm not supposed to do that when I'm planning to inject the router file directly into my test file. So I moved all the `Vue.use(xxx)` statements to main.js file. It solved the issue
