### ISSUE TITLE
Including Vue-Test-Utils in preexisting unit tests using PhantomJS

### ISSUE THREAD

**Issue by gplusdotgr** [vuejs/vue-test-utils#496]
I understand this issue does not conform with the guidelines but I am coming here after trying to get help in the Discord channel unsuccessfully due to the complexity of our app.

We have a large scale, [industrial app](http://tracking.here.com/), which codebase has many tests written using Mocha/Sinon and Karma. We use the PhantomJS browser.

We recently started investigating integrating vue-test-utils to write tests more efficiently.

I added the npm package, `    "@vue/test-utils": "1.0.0-beta.13",` the karma jsdom launcher, and added one dummy test to get started. 

```
import { mount } from '@vue/test-utils';
import CreateGeofence from './create';

describe('Foo', () => {
  it('renders a div', () => {
    const wrapper = mount(CreateGeofence);
    // console.log(wrapper);
    expect(wrapper.contains('div')).to.be.equal(true);
    // wrapper.find('.input-zoom').trigger('change');
  });
});
```

which, fails:

```
FAILED TESTS:
  Foo
    ✖ renders a div
      Mozilla/5.0 (darwin) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/11.6.2
      PhantomJS 2.1.1 (Mac OS X 0.0.0)
    expected false to equal true

      + expected - actual

      -false
      +true

```

This is how my karma.conf looks like:

```
module.exports = (config) => {
  config.set({
    // to run in additional browsers:
    //   1. install corresponding karma launcher http://karma-runner.github.io/0.13/config/browsers.html
    //   2. add it to the `browsers` array below.
    browsers: ['PhantomJS', 'jsdom'],
    frameworks: ['mocha', 'sinon-chai'],
    reporters: ['mocha', 'coverage'],
     // more stuff here
```

So, I am getting now many failures in my pre-existing tests, stuff like:
```
      ✖ "after each" hook for "should return true if it does not expire within 10 seconds"
        Mozilla/5.0 (darwin) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/11.6.2
      TypeError: Cannot read property 'restore' of undefined
          at Context.<anonymous> (base/index.js?305a22d66e659861e877414883acec8cbbf1a17d:274443:19)
          at Timeout.callback [as _onTimeout] (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/browser/Window.js:633:19)
          at ontimeout (timers.js:458:11)
          at tryOnTimeout (timers.js:296:5)
          at Timer.listOnTimeout (timers.js:259:5)
```

and at the end of my tests I get a series of
```
Error: Promise rejected with value: undefined
    at /Users/katsanos/frontend/node_modules/loud-rejection/index.js:27:12
    at Array.forEach (<anonymous>)
    at EventEmitter.<anonymous> (/Users/katsanos/frontend/node_modules/loud-rejection/index.js:23:24)
    at EventEmitter.emit (events.js:160:13)
    at emit (/Users/katsanos/frontend/node_modules/signal-exit/index.js:77:11)
    at processEmit [as emit] (/Users/katsanos/frontend/node_modules/signal-exit/index.js:150:5)
    at process.exit (internal/process.js:147:15)
    at removeAllListeners (/Users/katsanos/frontend/node_modules/karma/lib/server.js:421:7)
    at Server.<anonymous> (/Users/katsanos/frontend/node_modules/karma/lib/server.js:432:9)
    at Object.onceWrapper (events.js:255:19)
    at Server.emit (events.js:165:20)
    at emitCloseNT (net.js:1677:8)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

What is happening there?

**Comment by eddyerburgh** [comment]
Can you create a minimal reproduction? I can't see . what's going wrong from the stack trace.

**Comment by gplusdotgr** [comment]
@eddyerburgh I think it would already be enough if you could help us figure out if jsdom is a hard dependency on vue-test-utils or PhantomJS or Chrome can be used instead? We have many tests in our codebase and they break when we add jsdom to the karma configuration.

**Comment by eddyerburgh** [comment]
JSDOM isn't a hard dependency, you can run Vue Test Utils in any browser including phantom :).
