### ISSUE TITLE
Cannot reassign same class name to stub Component - circular reference 

### ISSUE THREAD

**Issue by trollepierre** [vuejs/vue-test-utils#659]
### Version
1.0.0-beta.16

### Reproduction link
[http://google.com](http://google.com)

### Steps to reproduce
Error: [vue-test-utils]: options.stub cannot contain a circular reference
```
import { mount } from '@vue/test-utils'
import Component from './Component.vue'

describe('components | Component', () => {
  const stubs = {
    AppButton: '<div class="app-button"/>',
  }

  describe('template', () => {
    it('should mount', () => {
      mount(Component, { stubs })
    })
  })
})
```
___
```
<template>
    <app-button/>
</template>

<script>
  import AppButton from '../../../common/app-button/AppButton.vue'

  export default {
    name: 'Component',
    components: {
      AppButton,
    },
  }
</script>
```
___
```
<template>
  <div class="app-button"/>
</template>

<script>
  export default {
    name: 'AppButton',
  }
</script>
```

### What is expected?
No error

### What is actually happening?
```
Error: [vue-test-utils]: options.stub cannot contain a circular reference
at throwError (mypath/node_modules/@vue/test-utils/dist/vue-test-utils.js:11:9)
at createStubFromString (mypath/node_modules/@vue/test-utils/dist/vue-test-utils.js:3968:5)
at mypath/node_modules/@vue/test-utils/dist/vue-test-utils.js:4019:30
at Array.forEach (<anonymous>)
at createComponentStubs (mypath/node_modules/@vue/test-utils/dist/vue-test-utils.js:3999:24)
at createInstance (mypath/node_modules/@vue/test-utils/dist/vue-test-utils.js:4208:24)
at mount (mypath/node_modules/@vue/test-utils/dist/vue-test-utils.js:5376:12)
at Object.<anonymous> (mypath/src/components/pages/request-workers-edition/aside-manager/Component.spec.js:11:7)
at Object.asyncFn (mypath/node_modules/jest-jasmine2/build/jasmine_async.js:82:37)
at resolve (mypath/node_modules/jest-jasmine2/build/queue_runner.js:52:12)
at new Promise (<anonymous>)
at mapper (mypath/node_modules/jest-jasmine2/build/queue_runner.js:39:19)
at promise.then (mypath/node_modules/jest-jasmine2/build/queue_runner.js:73:82)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by trollepierre** [comment]
@eddyerburgh : when will be the next release of vue-test-utils ?
I want to test this issue, and I have found maybe other issues that might be already solved...
Thanks

**Comment by eddyerburgh** [comment]
I'll make a release later this week
