### ISSUE TITLE
TypeError: Cannot read property '$options' of undefined

### ISSUE THREAD

**Issue by feliupe** [vuejs/vue-test-utils#673]
### Version
1.0.0-beta.15

### Reproduction link
[https://github.com/feliupe/vuerror](https://github.com/feliupe/vuerror)

### Steps to reproduce
yarn && yarn test

### What is expected?
The test to run with no error.

### What is actually happening?
There two errors:

- `    TypeError: Cannot read property '$options' of undefined`
- and `    TypeError: Cannot set property '_error' of undefined`, that I think is related to the errorHandler and my not be related to the test failing.

```
    TypeError: Cannot read property '$options' of undefined

       6 |     it('Mock', () => {
       7 |         const wrapper = mount(Page)
    >  8 |         wrapper.vm.treeData = {}
       9 |         // wrapper.vm.$forceUpdate()
      10 |     })
      11 | })
      
      at updateChildComponent (node_modules/vue/dist/vue.js:2573:8)
      at prepatch (node_modules/vue/dist/vue.js:3510:5)
      at patchVnode (node_modules/vue/dist/vue.js:5425:7)
      at updateChildren (node_modules/vue/dist/vue.js:5340:9)
      at patchVnode (node_modules/vue/dist/vue.js:5436:29)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.js:5566:9)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.js:2428:19)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.js:2542:10)
      at Watcher.get (node_modules/vue/dist/vue.js:2883:25)
      at Watcher.run (node_modules/vue/dist/vue.js:2960:22)
      at Watcher.update (node_modules/vue/dist/vue.js:2948:10)
      at Dep.notify (node_modules/vue/dist/vue.js:784:13)
      at Object.reactiveSetter [as treeData] (node_modules/vue/dist/vue.js:1006:11)
      at updateChildComponent (node_modules/vue/dist/vue.js:2599:18)
      at prepatch (node_modules/vue/dist/vue.js:3510:5)
      at patchVnode (node_modules/vue/dist/vue.js:5425:7)
      at updateChildren (node_modules/vue/dist/vue.js:5340:9)
      at patchVnode (node_modules/vue/dist/vue.js:5436:29)
      at updateChildren (node_modules/vue/dist/vue.js:5340:9)
      at patchVnode (node_modules/vue/dist/vue.js:5436:29)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.js:5566:9)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.js:2428:19)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.js:2542:10)
      at Watcher.get (node_modules/vue/dist/vue.js:2883:25)
      at Watcher.run (node_modules/vue/dist/vue.js:2960:22)
      at Watcher.update (node_modules/vue/dist/vue.js:2948:10)
      at VueComponent.Vue.$forceUpdate (node_modules/vue/dist/vue.js:2449:19)
      at updateChildComponent (node_modules/vue/dist/vue.js:2615:8)
      at prepatch (node_modules/vue/dist/vue.js:3510:5)
      at patchVnode (node_modules/vue/dist/vue.js:5425:7)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.js:5566:9)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.js:2428:19)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.js:2542:10)
      at Watcher.get (node_modules/vue/dist/vue.js:2883:25)
      at Watcher.run (node_modules/vue/dist/vue.js:2960:22)
      at Watcher.update (node_modules/vue/dist/vue.js:2948:10)
      at Dep.notify (node_modules/vue/dist/vue.js:784:13)
      at Object.reactiveSetter [as treeData] (node_modules/vue/dist/vue.js:1006:11)
      at VueComponent.proxySetter [as treeData] (node_modules/vue/dist/vue.js:3075:26)
      at Object.it (test/Test.spec.js:8:9)

  console.error node_modules/vue/dist/vue.js:667
    TypeError: Cannot set property '_error' of undefined
        at errorHandler (/home/feliupe/archii/vuerror/node_modules/@vue/test-utils/dist/vue-test-utils.js:5126:13)
        at handleError (/home/feliupe/archii/vuerror/node_modules/vue/dist/vue.js:565:25)
        at Array.<anonymous> (/home/feliupe/archii/vuerror/node_modules/vue/dist/vue.js:709:11)
        at nextTickHandler (/home/feliupe/archii/vuerror/node_modules/vue/dist/vue.js:654:16)
        at <anonymous>
```

---
I tried to create the minimum setup to reproduce the problem. Almost any statement you remove from this code will make the test pass. Like removing `<message/>` for example. 

You may ask, why this setup of components, with a `Tree` and `Message` wrapped in a `Layout`: it's a representation of what I have in my project.

May also help to know that the error disappears if you remove `wrapper.vm.treeData = {}` and also happens if you uncomment `wrapper.vm.$forceUpdate()`.

**Comment by eddyerburgh** [comment]
Thanks for the bug report.

This is the same issue filed here—#653.

This is a problem with how we have implemented synchronous updating. There's a PR open to fix this by adding an async option to Vue—https://github.com/vuejs/vue/pull/8240.

For the moment, the workaround is to set the `sync` mounting option to false and use Vue.nextTick to await DOM updates:

```js
test('use Vue.nextTick', (done) => {
  const wrapper = mount(TestComponent, { sync: false })
  wrapper.trigger('click')
  Vue.nextTick(() => {
    expect(wrapper.text()).toBe('updated')
    done()
  })
})
```

**Comment by nathan-isaac** [comment]
I ran into this issue myself. However, I couldn't get Edd Yerburgh solution to work for me. I was working with a form submit trigger event. 

~~I ended up using the `flushPromises` method from https://www.npmjs.com/package/flush-promises.~~

```js
test('use Vue.nextTick', async () => {
  const wrapper = mount(TestComponent, { sync: false })
  wrapper.trigger('submit')
  await flushPromises()
  expect(wrapper.text()).toBe('updated')
})
```
## Update 

My above example actually didn't work as expected. Here is what I changed. 

```js
test('use Vue.nextTick', async () => {
  const wrapper = mount(TestComponent, { sync: false })
  wrapper.trigger('submit')
  await wrapper.vm.$nextTick()
  expect(wrapper.text()).toBe('updated')
})
```

**Comment by mwangaben** [comment]
@nathanjisaac thanks men this is huge serve !

**Comment by rndmerle** [comment]
I've updated to @vue/test-utils 1.0.0-beta.29 and vue 2.5.22 and I've the same issue.

I pulled out a minimal reproduction on https://github.com/rndmerle/repro-vue-test-utils-sync.git
Just `yarn && yarn test`

The test would pass if you change either one of those:
- comment out one of the two it()
- comment out the content of the forEach (in setup method)
- switch the watcher to immediate:false and uncomment the created() content

I can't find anything further down, my brain is boiling.

**Comment by eddyerburgh** [comment]
Thanks for the reproduction @rndmerle, this is caused by `sync` mode, which is being deprecated. See this issue for more details—https://github.com/vuejs/vue-test-utils/issues/1137

**Comment by rndmerle** [comment]
Yea but I thought https://github.com/vuejs/vue-test-utils/pull/1062 would solve that somehow. I misunderstood something I guess.
Thanks for the details.

**Comment by eddyerburgh** [comment]
We were hoping #1062 would be a medium-term solution, but there are lots of edge cases we didn't anticipate.

**Comment by rndmerle** [comment]
It's clearer now thanks ;)

**Comment by k2042** [comment]
Hello. I believe I ran into the same issue using Kendo Chart. I'm using the second one from here: https://www.telerik.com/kendo-vue-ui/components/charts/series-types/area/ Basically copying the whole example into a default Vue project.

> {
>   "name": "chart-test",
>   "version": "0.1.0",
>   "private": true,
>   "scripts": {
>     "serve": "vue-cli-service serve",
>     "build": "vue-cli-service build",
>     "lint": "vue-cli-service lint"
>   },
>   "dependencies": {
>     "@progress/kendo-charts-vue-wrapper": "^2021.1.119",
>     "@progress/kendo-theme-default": "^4.33.0",
>     "@progress/kendo-ui": "^2021.1.119",
>     "core-js": "^3.6.5",
>     "vue": "2.6.12"
>   },
>   "devDependencies": {
>     "@vue/cli-plugin-babel": "^4.5.0",
>     "@vue/cli-plugin-eslint": "^4.5.0",
>     "@vue/cli-service": "^4.5.0",
>     "babel-eslint": "^10.1.0",
>     "eslint": "^6.7.2",
>     "eslint-plugin-vue": "^6.2.2",
>     "vue-template-compiler": "2.6.12"
>   },
>   "eslintConfig": {
>     "root": true,
>     "env": {
>       "node": true
>     },
>     "extends": [
>       "plugin:vue/essential",
>       "eslint:recommended"
>     ],
>     "parserOptions": {
>       "parser": "babel-eslint"
>     },
>     "rules": {}
>   },
>   "browserslist": [
>     "> 1%",
>     "last 2 versions",
>     "not dead"
>   ]
> }

As it reports, Vue is of version 2.6.12, as the chart wrapper requires. As I load the page with the chart I get the following error: 

> Error in mounted hook: "TypeError: Cannot read property '$options' of undefined"
> found in
> ---> <KendoChart>
> ...

Since there already was a fix PR into Vue 2, I suppose there is a combination of versions between Vue 2 and Kendo that should actually work, is there?
