### ISSUE TITLE
I am not able to remove this error (   [Vue warn]: Failed to mount component: template or render function not defined. )?

### ISSUE THREAD

**Issue by codeimmortal** [vuejs/vue-test-utils#817]
The code i use is this . Test cases are pass but it has this warnings

I am using JEST .

code i use something like this. what is wrong with it can you tell me . It gives me warning .

```
import Vue from "vue";
import Vuex from "vuex";
import Router from "vue-router";
import BootstrapVue from "bootstrap-vue";
import Loading from "vue-loading-overlay";
import X2JS from "x2js";

const x2js = new X2JS();
import {  getResponseJSON } from "../src/util/utility";

import {
    serviceURL
} from "../src/util/config";

import {
    shallowMount,
    mount,
    createLocalVue
} from '@vue/test-utils'
Vue.use(BootstrapVue);
import axios from 'axios'

jest.mock('axios', () => ({
    post: jest.fn(() => Promise.resolve({
        data: [3]
    }))
}))
// add the 2 lines below
// const localVue = createLocalVue();
// localVue.use(Vuex);
Vue.use(Vuex);
Vue.use(Router);
Vue.use(Loading);
import AddEditPerson from "../src/components/AddEditPerson/AddEditPerson.vue";
const localVue = createLocalVue();
localVue.use(Vuex);
describe("AddPerson.test.js", () => {
    let cmp, store, actions, router;
    beforeEach(() => {
        cmp = Vue.extend(AddEditPerson);
        store = new Vuex.Store({
            state: {},
            actions
        });
        router = new Router({
            routes: []
        });
    });
 it("Clicking on membership will active that tab", () => {
        let check = false;
        let wrapper = shallowMount(AddEditPerson, {
            localVue,
            store,
            router
        });
        if(wrapper.vm.memberships.length > 0){
            check = true;
        }
        expect(check).toEqual(true);
    });

    it('has the expected html structure', () => {
        let wrapper = mount(AddEditPerson, {
            localVue,
            store,
            router
        });
        expect(wrapper.vm.$el).toMatchSnapshot();
    });
});
```

Error on console .  

console.error node_modules/vue/dist/vue.common.js:593
      [Vue warn]: Failed to mount component: template or render function not defined.

      found in

      ---> <Taxonomy>
             <BTab>
               <BTabs>
                 <AddEditPerson>
                   <Root>
    console.error node_modules/vue/dist/vue.common.js:593
      [Vue warn]: Failed to mount component: template or render function not defined.

      found in

      ---> <Taxonomy>
             <BTab>
               <BTabs>
                 <AddEditPerson>
                   <Root>
    console.error node_modules/vue/dist/vue.common.js:593
      [Vue warn]: Failed to mount component: template or render function not defined.

      found in

      ---> <Taxonomy>
             <BTab>
               <BTabs>
                 <AddEditPerson>
                   <Root>
    console.log test/addEditPerson.test.js:98
      [Function: mount]
    console.error node_modules/vue/dist/vue.common.js:593
      [Vue warn]: Failed to mount component: template or render function not defined.

      found in

      ---> <Taxonomy>
             <BTab>
               <BTabs>
                 <AddEditPerson>
                   <Root>
    console.log test/addEditPerson.test.js:111
      Wrapper { version: 2.5 }
    console.error node_modules/vue/dist/vue.common.js:593
      [Vue warn]: Failed to mount component: template or render function not defined.

      found in

      ---> <Taxonomy>
             <BTab>
               <BTabs>
                 <AddEditPerson>
                   <Root>
    console.error node_modules/vue/dist/vue.common.js:593
      [Vue warn]: Failed to mount component: template or render function not defined.

      found in

      ---> <Taxonomy>
             <BTab>
               <BTabs>
                 <AddEditPerson>
                   <Root>
    console.error node_modules/vue/dist/vue.common.js:593
      [Vue warn]: Failed to mount component: template or render function not defined.

      found in

      ---> <Taxonomy>
             <BTab>
               <BTabs>
                 <AddEditPerson>
                   <Root>
    console.error node_modules/vue/dist/vue.common.js:593
      [Vue warn]: Error in event handler for "input": "TypeError: Cannot read property '_transitionClasses' of undefined"

      found in

      ---> <BFormInput>
             <Autocomplete>
               <BTab>
                 <BTabs>
                   <AddEditPerson>
                     <Root>
    console.error node_modules/vue/dist/vue.common.js:1743
      TypeError: Cannot read property '_transitionClasses' of undefined
          at Array.updateClass (c:\someapp\node_modules\vue\dist\vue.common.js:6430:28)
          at patchVnode (c:\someapp\node_modules\vue\dist\vue.common.js:5933:62)
          at updateChildren (c:\someapp\node_modules\vue\dist\vue.common.js:5824:9)
          at patchVnode (c:\someapp\node_modules\vue\dist\vue.common.js:5938:29)
          at updateChildren (c:\someapp\node_modules\vue\dist\vue.common.js:5824:9)
          at patchVnode (c:\someapp\node_modules\vue\dist\vue.common.js:5938:29)
          at VueComponent.patch [as __patch__] (c:\someapp\node_modules\vue\dist\vue.common.js:6098:9)
          at VueComponent.Vue._update (c:\someapp\node_modules\vue\dist\vue.common.js:2672:19)
          at VueComponent.vm._update (c:\someapp\node_modules\@vue\test-utils\dist\vue-test-utils.js:4326:12)
          at VueComponent.updateComponent (c:\someapp\node_modules\vue\dist\vue.common.js:2790:10)
          at Watcher.get (c:\someapp\node_modules\vue\dist\vue.common.js:3144:25)
          at Watcher.run (c:\someapp\node_modules\vue\dist\vue.common.js:3221:22)
          at Watcher.update (c:\someapp\node_modules\vue\dist\vue.common.js:3209:10)
          at Dep.notify (c:\someapp\node_modules\vue\dist\vue.common.js:699:13)
          at Object.reactiveSetter [as showValue] (c:\someapp\node_modules\vue\dist\vue.common.js:1016:11)
          at Proxy.proxySetter (c:\someapp\node_modules\vue\dist\vue.common.js:3302:26)
          at callback (c:\someapp\src\components\autocomplete\autocomplete.vue:193:582)
          at VueComponent.invoker (c:\someapp\node_modules\vue\dist\vue.common.js:2029:18)
          at VueComponent.Vue.$emit (c:\someapp\node_modules\vue\dist\vue.common.js:2540:18)
          at VueComponent.setValue (c:\someapp\node_modules\bootstrap-vue\src\components\form-input\form-input.js:140:12)
          at VueComponent.value (c:\someapp\node_modules\bootstrap-vue\src\components\form-input\form-input.js:128:14)
          at Watcher.run (c:\someapp\node_modules\vue\dist\vue.common.js:3235:19)
          at Watcher.update (c:\someapp\node_modules\vue\dist\vue.common.js:3209:10)
          at Dep.notify (c:\someapp\node_modules\vue\dist\vue.common.js:699:13)
          at Object.reactiveSetter [as value] (c:\someapp\node_modules\vue\dist\vue.common.js:1016:11)
          at updateChildComponent (c:\someapp\node_modules\vue\dist\vue.common.js:2851:18)
          at prepatch (c:\someapp\node_modules\vue\dist\vue.common.js:4146:5)
          at patchVnode (c:\someapp\node_modules\vue\dist\vue.common.js:5927:7)
          at updateChildren (c:\someapp\node_modules\vue\dist\vue.common.js:5824:9)
          at patchVnode (c:\someapp\node_modules\vue\dist\vue.common.js:5938:29)
          at VueComponent.patch [as __patch__] (c:\someapp\node_modules\vue\dist\vue.common.js:6098:9)
          at VueComponent.Vue._update (c:\someapp\node_modules\vue\dist\vue.common.js:2672:19)
          at VueComponent.vm._update (c:\someapp\node_modules\@vue\test-utils\dist\vue-test-utils.js:4326:12)
          at VueComponent.updateComponent (c:\someapp\node_modules\vue\dist\vue.common.js:2790:10)
          at Watcher.get (c:\someapp\node_modules\vue\dist\vue.common.js:3144:25)
          at Watcher.run (c:\someapp\node_modules\vue\dist\vue.common.js:3221:22)
          at Watcher.update (c:\someapp\node_modules\vue\dist\vue.common.js:3209:10)
          at Dep.notify (c:\someapp\node_modules\vue\dist\vue.common.js:699:13)
          at Object.reactiveSetter [as showValue] (c:\someapp\node_modules\vue\dist\vu

**Comment by adamchenwei** [comment]
same issue

**Comment by luckylooke** [comment]
Same, test passes but error at the end 🤷 
```
 PASS  src/components/BillingProfile.spec.ts (6.001s)
  BillingProfile
    ✓ renders a signup form when user is not logged in (20ms)

  console.error node_modules/vue/dist/vue.runtime.common.dev.js:621
    [Vue warn]: Failed to mount component: template or render function not defined.
    
    found in
    
    ---> <Anonymous>
           <Root>

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        7.672s
Ran all test suites matching /bill/i.

Watch Usage: Press w to show more.
```
