### ISSUE TITLE
Property named "parent" not supported during mount

### ISSUE THREAD

**Issue by zachmullen** [vuejs/vue-test-utils#909]
### Version
1.0.0-beta.24

### Reproduction link
[https://github.com/girder/girder_web_components/tree/vue-test-utils-bug](https://github.com/girder/girder_web_components/tree/vue-test-utils-bug)

### Steps to reproduce
1. Checkout the above git branch. I realize it's not strictly minimal, but it's minimal in the sense that it's a [minimal change](https://github.com/girder/girder_web_components/commit/209596a7de4a5315440d1db899905fbfb7fbe03a) from the raw template output from vue-init (version 3).
2. `yarn && yarn test:unit`

### What is expected?
The HelloWorld test should pass, and it *does*, if the prop name is something other than `parent`.

### What is actually happening?
```
1 failing

  1) HelloWorld.vue
       renders props.msg when passed:
     TypeError: Cannot read property 'parent' of undefined
      at VueComponent.proxyGetter [as parent] (dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:3293:1)
      at VueComponent.hook (dist/webpack:/node_modules/vue-loader/lib/runtime/componentNormalizer.js:46:1)
      at callHook (dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:2917:1)
      at VueComponent.Vue._init (dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:4622:1)
      at new VueComponent (dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:4794:1)
      at createComponentInstanceForVnode (dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:4306:1)
      at init (dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:4127:1)
      at createComponent (dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:5604:1)
      at createElm (dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:5551:1)
      at VueComponent.patch [as __patch__] (dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:6087:1)
      at VueComponent.Vue._update (dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:2656:1)
      at VueComponent.updateComponent (dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:2784:1)
      at Watcher.get (dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:3138:1)
      at new Watcher (dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:3127:1)
      at mountComponent (dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:2791:1)
      at VueComponent../node_modules/vue/dist/vue.runtime.esm.js.Vue.$mount (dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:7995:1)
      at mount (dist/webpack:/node_modules/@vue/test-utils/dist/vue-test-utils.js:5542:1)
      at shallowMount (dist/webpack:/node_modules/@vue/test-utils/dist/vue-test-utils.js:5579:1)
      at Context.<anonymous> (dist/webpack:/tests/unit/HelloWorld.spec.js:8:1)
```

**Comment by eddyerburgh** [comment]
This is actually an issue with @vue/cli-plugin-unit-mocha/ vue-loader. I've created a new issue there https://github.com/vuejs/vue-cli/issues/2270

**Comment by zachmullen** [comment]
Thanks!
